import {useCallback, useLayoutEffect, useRef, useState, useSyncExternalStore} from 'react'
import {CheckCircle, Info, WarningCircle, X, XCircle} from '@phosphor-icons/react'
import {useTranslation} from 'react-i18next'

type ToastVariant='default'|'accent'|'success'|'warning'|'danger'
type ToastOptions={description?:string;variant?:ToastVariant;timeout?:number}
type ToastItem={id:number;title:string;description?:string;variant:ToastVariant;phase:'entering'|'visible'|'exiting';exitIndex?:number}
type AutoTimer={handle:ReturnType<typeof setTimeout>|null;deadline:number;remaining:number}
let items:ToastItem[]=[];let nextId=1;let timersPaused=false;const listeners=new Set<()=>void>();const autoTimers=new Map<number,AutoTimer>()
const emit=()=>listeners.forEach(listener=>listener());const subscribe=(listener:()=>void)=>{listeners.add(listener);return()=>listeners.delete(listener)};const snapshot=()=>items
const remove=(id:number)=>{autoTimers.delete(id);items=items.filter(item=>item.id!==id);emit()}
const close=(id:number)=>{const exitIndex=items.filter(item=>item.phase!=='exiting').findIndex(item=>item.id===id);if(exitIndex<0)return;const timer=autoTimers.get(id);if(timer?.handle)clearTimeout(timer.handle);autoTimers.delete(id);items=items.map(item=>item.id===id?{...item,phase:'exiting',exitIndex}:item);emit();setTimeout(()=>remove(id),350)}
const schedule=(id:number,remaining:number)=>{if(timersPaused){autoTimers.set(id,{deadline:0,remaining,handle:null});return}const deadline=Date.now()+remaining;autoTimers.set(id,{deadline,remaining,handle:setTimeout(()=>close(id),remaining)})}
const pauseAll=()=>{timersPaused=true;autoTimers.forEach((timer,id)=>{if(timer.handle)clearTimeout(timer.handle);autoTimers.set(id,{handle:null,deadline:0,remaining:timer.handle?Math.max(0,timer.deadline-Date.now()):timer.remaining})})}
const resumeAll=()=>{timersPaused=false;autoTimers.forEach((timer,id)=>schedule(id,timer.remaining))}
const add=(title:string,options:ToastOptions={})=>{const id=nextId++;items=[{id,title,description:options.description,variant:options.variant??'default',phase:'entering'},...items];emit();requestAnimationFrame(()=>requestAnimationFrame(()=>{items=items.map(item=>item.id===id&&item.phase==='entering'?{...item,phase:'visible'}:item);emit()}));const timeout=options.timeout??4000;if(timeout>0)schedule(id,timeout);return id}
export const toast=Object.assign(add,{success:(title:string,options:Omit<ToastOptions,'variant'>={})=>add(title,{...options,variant:'success'}),danger:(title:string,options:Omit<ToastOptions,'variant'>={})=>add(title,{...options,variant:'danger'}),info:(title:string,options:Omit<ToastOptions,'variant'>={})=>add(title,{...options,variant:'accent'}),warning:(title:string,options:Omit<ToastOptions,'variant'>={})=>add(title,{...options,variant:'warning'}),close,clear:()=>items.forEach(item=>close(item.id)),pauseAll,resumeAll})
const icons={default:Info,accent:Info,success:CheckCircle,warning:WarningCircle,danger:XCircle}
function AppToast({item,index,expanded,frontHeight,expandedOffset,onHeight,onExpand}:{item:ToastItem;index:number;expanded:boolean;frontHeight:number;expandedOffset:number;onHeight:(id:number,height:number)=>void;onExpand:()=>void}){const{t}=useTranslation();const ref=useRef<HTMLDivElement>(null);const Icon=icons[item.variant];const hidden=index>=3;useLayoutEffect(()=>{const el=ref.current;if(!el)return;const measure=()=>onHeight(item.id,el.scrollHeight);measure();const observer=new ResizeObserver(measure);observer.observe(el);return()=>observer.disconnect()},[item.id,onHeight]);return <div ref={ref} className={`app-toast app-toast--${item.variant} is-${item.phase}${index===0?' is-frontmost':''}${hidden?' is-hidden':''}`} style={{'--toast-y':`${expanded?expandedOffset:index*12}px`,'--toast-scale':expanded?1:1-index*.05,'--toast-opacity':expanded&&!hidden?1:hidden?0:1,'--front-height':`${frontHeight}px`,'--toast-z':items.length-index} as React.CSSProperties} role={item.variant==='danger'?'alert':'status'} aria-hidden={hidden} aria-live={item.variant==='danger'?'assertive':'polite'} tabIndex={index===0?0:-1} onMouseEnter={onExpand}><Icon className="app-toast__icon" size={18} weight="duotone"/><span className="app-toast__content"><strong>{item.title}</strong>{item.description?<small>{item.description}</small>:null}</span><button className="app-toast__close" aria-label={t('toast.close')} title={t('toast.close')} onClick={()=>close(item.id)}><X size={12} weight="bold"/></button></div>}
export function AppToastProvider(){const{t}=useTranslation();const current=useSyncExternalStore(subscribe,snapshot,snapshot);const[expanded,setExpanded]=useState(false);const[heights,setHeights]=useState<Record<number,number>>({});const setHeight=useCallback((id:number,height:number)=>setHeights(previous=>previous[id]===height?previous:{...previous,[id]:height}),[]);const active=current.filter(item=>item.phase!=='exiting');const frontHeight=heights[active[0]?.id]??56;const totalVisible=active.slice(0,3).reduce((sum,item)=>sum+(heights[item.id]??frontHeight)+12,-12);return <div className={`app-toast-region${expanded?' is-expanded':''}`} style={{'--toast-region-height':`${Math.max(120,totalVisible)}px`} as React.CSSProperties} aria-label={t('toast.region')} onMouseLeave={()=>{setExpanded(false);resumeAll()}}>{current.map(item=>{const index=item.phase==='exiting'?item.exitIndex??0:active.indexOf(item);return <AppToast key={item.id} item={item} index={index} expanded={expanded} frontHeight={frontHeight} expandedOffset={active.slice(0,index).reduce((sum,previous)=>sum+(heights[previous.id]??frontHeight)+12,0)} onHeight={setHeight} onExpand={()=>{if(!expanded){setExpanded(true);pauseAll()}}}/>})}</div>}
