import {useEffect,useMemo,useRef,useState} from 'react'
import {Button} from '@heroui/react'
import {Dialogs} from '@wailsio/runtime'
import {Copy,DownloadSimple,File as FileIcon,FileImage,Trash,UploadSimple} from '@phosphor-icons/react'
import {useTranslation} from 'react-i18next'
import CodeMirror from '@uiw/react-codemirror'
import {EditorView} from '@codemirror/view'
import {tokyoNight} from '@uiw/codemirror-theme-tokyo-night'
import {tokyoNightDay} from '@uiw/codemirror-theme-tokyo-night-day'
import {SaveBase64File} from '../../bindings/changeme/configservice'
import {Reveal,ToolHeader,type PendingAction,type ToolId} from './shared'
import {toast} from './AppToast'
type OutputKind='text'|'image'|'file'
type FileInfo={name:string;type:string;size:number;data:string;image:boolean}
type OutputFile={name:string;mime:string;size:number;data:string}
const MAX_BYTES=100*1024*1024
const bytesLabel=(n:number)=>n<1024?`${n} B`:n<1024*1024?`${(n/1024).toFixed(1)} KB`:`${(n/1024/1024).toFixed(1)} MB`
function rawBase64(value:string){const raw=value.trim().replace(/^data:[^,]+,/,'').replace(/^,/,'').replace(/\s/g,'');return raw.length>=4&&(raw.includes('=')||raw.length>=24)&&raw.length<=Math.ceil(MAX_BYTES*4/3)&&!raw.includes('.')&&/^[A-Za-z0-9+/_-]+={0,2}$/.test(raw)&&raw.length%4!==1?raw:''}
function isImage(value:string){try{const raw=value.replace(/-/g,'+').replace(/_/g,'/');const b=Uint8Array.from(atob(raw.slice(0,128)),c=>c.charCodeAt(0));return(b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47)||(b[0]===0xff&&b[1]===0xd8)||String.fromCharCode(...b.slice(0,6)).startsWith('GIF')||String.fromCharCode(...b.slice(8,12))==='WEBP'}catch{return false}}
export default function Base64Tool({active,theme,record,pending,clearPending}:{active:boolean;theme:string;record:(tool:ToolId,action:string,detail:string,input:string,output?:string,meta?:{mode:string;mediaType?:string;name?:string;bytes?:number})=>void;pending:PendingAction|null;clearPending:()=>void}){const{t}=useTranslation();const[input,setInput]=useState('');const[sourceFile,setSourceFile]=useState<FileInfo|null>(null);const[output,setOutput]=useState('');const[outputKind,setOutputKind]=useState<OutputKind>('text');const[outputFile,setOutputFile]=useState<OutputFile|null>(null);const[fileInput,setFileInput]=useState<HTMLInputElement|null>(null);const worker=useRef<Worker|null>(null);const consumed=useRef<PendingAction|null>(null);const revision=useRef(0);const cmTheme=theme==='light'?tokyoNightDay:tokyoNight;const extensions=useMemo(()=>[EditorView.lineWrapping],[]);const run=(action:'encode'|'decodeText'|'decodeImage'|'decodeFile',value:string)=>new Promise<{output:string;bytes:number;mime?:string;ext?:string}>((resolve,reject)=>{worker.current?.terminate();const next=new Worker(new URL('../utils/base64.worker.ts',import.meta.url),{type:'module'});worker.current=next;next.onmessage=e=>{next.terminate();e.data.error?reject(new Error('invalid')):resolve(e.data)};next.postMessage({id:1,action,input:value})});useEffect(()=>()=>worker.current?.terminate(),[])
const showText=(value:string,bytes:number)=>{setOutputKind('text');setOutputFile(null);setOutput(value);return bytes};const showMedia=(kind:'image'|'file',result:{output:string;bytes:number;mime?:string;ext?:string})=>{const ext=result.ext??'bin';setOutputKind(kind);setOutput(result.output);setOutputFile({name:`decoded.${ext}`,mime:result.mime??'application/octet-stream',size:result.bytes,data:result.output})}
const convert=async(value:string)=>{const id=++revision.current;const raw=rawBase64(value);try{if(/^data:/i.test(value.trim())){const data=value.trim();if(id!==revision.current)return;showText(data.replace(/^data:[^,]+,/,''),Math.floor(data.length*.75));return}if(raw){if(isImage(raw)){const result=await run('decodeImage',raw);if(id!==revision.current)return;showMedia('image',result);return}try{const result=await run('decodeText',raw);if(id!==revision.current)return;showText(result.output,result.bytes)}catch{if(id!==revision.current)return;const result=await run('decodeFile',raw);if(id!==revision.current)return;showMedia('file',result)}return}const result=await run('encode',value);if(id!==revision.current)return;showText(result.output,result.bytes)}catch{if(id===revision.current){setOutputKind('text');setOutputFile(null);setOutput('');toast(t('base64Tool.invalid'),{variant:'warning'})}}}
useEffect(()=>{const timer=window.setTimeout(()=>void convert(input),input.length>1024*1024?180:80);return()=>window.clearTimeout(timer)},[input])
useEffect(()=>{if(!pending||pending.tool!=='base64'||consumed.current===pending)return;consumed.current=pending;clearPending();setSourceFile(null);setInput(pending.input)},[pending])
const load=async(file:File)=>{if(file.size>MAX_BYTES){toast(t('base64Tool.tooLarge',{size:bytesLabel(MAX_BYTES)}),{variant:'warning'});return}try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(file)});const info={name:file.name,type:file.type||'application/octet-stream',size:file.size,data,image:file.type.startsWith('image/')};setSourceFile(info);setInput(data);record('base64',t('base64Tool.encoded'),`${info.image?t('base64Tool.image'):t('base64Tool.file')} · ${bytesLabel(file.size)}`,data,data.replace(/^data:[^,]+,/,''),{mode:info.image?'image':'file',mediaType:info.type,name:file.name,bytes:file.size})}catch{toast(t('base64Tool.invalid'),{variant:'danger'})}}
const paste=(e:React.ClipboardEvent<HTMLDivElement>)=>{const file=e.clipboardData.files[0];if(file){e.preventDefault();void load(file)}};const drop=(e:React.DragEvent<HTMLDivElement>)=>{const file=e.dataTransfer.files[0];if(file){e.preventDefault();void load(file)}}
const save=async()=>{if(!outputFile)return;try{const path=await Dialogs.SaveFile({Title:t('base64Tool.saveTitle'),Filename:outputFile.name,ButtonText:t('base64Tool.save'),CanCreateDirectories:true});if(!path)return;await SaveBase64File(path,outputFile.data);toast(t('base64Tool.saved',{name:outputFile.name}),{variant:'success'})}catch{toast(t('base64Tool.saveFailed'),{variant:'danger'})}}
const textPane=(label:string,value:string,onChange?:(value:string)=>void)=><div className="editor base64-cm-pane"><span>{label}</span><CodeMirror className="base64-cm" height="100%" value={value} onChange={onChange} readOnly={!onChange} editable={!!onChange} theme={cmTheme} extensions={extensions} basicSetup={{lineNumbers:false,foldGutter:false,highlightActiveLine:false,highlightActiveLineGutter:false,autocompletion:false,closeBrackets:false}}/></div>
const filePane=(file:FileInfo)=><div className="editor base64-source-file"><span>{t('base64Tool.fileInput')}</span><div className="base64-source-content">{file.image?<img src={file.data} alt={file.name}/>:<FileIcon size={42} weight="duotone"/>}<div className="base64-file-caption"><strong>{file.name}</strong><small>{file.type} · {bytesLabel(file.size)}</small></div></div></div>
const outputPane=()=>{if(outputKind==='text')return textPane(t('base64Tool.output'),output);if(!outputFile)return null;return <div className="editor base64-output-media"><span>{outputKind==='image'?t('base64Tool.imageOutput'):t('base64Tool.fileOutput')}</span><div className="base64-output-content">{outputKind==='image'?<img src={outputFile.data} alt={outputFile.name}/>:<><FileIcon size={44} weight="duotone"/><strong>{t('base64Tool.binaryFile')}</strong></>}<footer><span><strong>{outputFile.name}</strong><small>{outputFile.mime} · {bytesLabel(outputFile.size)}</small></span><Button variant="secondary" onPress={save}><DownloadSimple weight="duotone"/>{t('base64Tool.save')}</Button></footer></div></div>}
const clear=()=>{setSourceFile(null);setInput('');setOutput('');setOutputKind('text');setOutputFile(null)}
return <Reveal index={0} active={active}><section className="tool-page base64-page"><ToolHeader title={t('base64Tool.title')} desc={t('base64Tool.subtitle')}/><div className="editor-grid base64-editors"><div className={`base64-input-stack${input&&!sourceFile?' has-text':''}${sourceFile?' has-file':''}`}>{sourceFile?filePane(sourceFile):<><div className="base64-input-text" onPaste={paste} onDragOver={e=>e.preventDefault()} onDrop={drop}>{textPane(t('base64Tool.input'),input,value=>{setSourceFile(null);setInput(value)})}</div>{!input&&<div className="base64-file-choice" onDragOver={e=>e.preventDefault()} onDrop={drop}><FileImage size={27} weight="duotone"/><span>{t('base64Tool.fileHint')}</span><Button variant="secondary" onPress={()=>fileInput?.click()}><UploadSimple weight="duotone"/>{t('base64Tool.chooseFile')}</Button><input ref={setFileInput} className="base64-file-input" type="file" onChange={e=>{const file=e.target.files?.[0];if(file)void load(file);e.currentTarget.value=''}}/></div>}</>}</div>{outputPane()}</div><div className="detected"><span>{t('base64Tool.detected')}</span><strong>{t(`base64Tool.${outputKind}`)} · {bytesLabel(sourceFile?.size??input.length)} → {bytesLabel(outputFile?.size??output.length)}</strong></div><div className="tool-actions">{outputKind==='text'&&<Button variant="tertiary" onPress={()=>{navigator.clipboard?.writeText(output);toast(t('toast.copied',{value:bytesLabel(output.length)}))}}><Copy weight="duotone"/>{t('base64Tool.copy')}</Button>}<Button variant="tertiary" onPress={clear}><Trash weight="duotone"/>{t('base64Tool.clear')}</Button></div></section></Reveal>}
