import {useEffect,useRef,useState} from 'react'
import {minimalSetup} from 'codemirror'
import {getChunks,MergeView,type Chunk} from '@codemirror/merge'
import {RangeSetBuilder} from '@codemirror/state'
import {Decoration,EditorView,type DecorationSet,ViewPlugin} from '@codemirror/view'
import {tokyoNight} from '@uiw/codemirror-theme-tokyo-night'
import {tokyoNightDay} from '@uiw/codemirror-theme-tokyo-night-day'
import {ArrowsLeftRight,FileCode,Trash} from '@phosphor-icons/react'
import {useTranslation} from 'react-i18next'
import {Reveal,ToolActionBar,ToolLayout,type PendingAction} from './shared'

type Counts={deletions:number;additions:number}
type HighlightMode='word-alt'|'word'|'character'|'none'
const diffTheme=EditorView.theme({'&':{height:'100%!important',overflow:'visible!important',font:'11px/1.55 var(--font-mono)',backgroundColor:'var(--surface)'},'.cm-scroller':{height:'100%!important',overflowY:'visible!important',fontFamily:'var(--font-mono)'},'.cm-content':{padding:'9px 0 20px'},'.cm-line':{padding:'0 12px 0 8px'},'.cm-gutters':{backgroundColor:'var(--surface-tertiary)',border:0,color:'var(--muted)',font:'10px/1.55 var(--font-mono)'},'.cm-gutterElement':{padding:'0 8px 0 10px',minWidth:'38px',textAlign:'right'},'.cm-changeGutter':{width:'3px',paddingLeft:'1px',background:'transparent'},'&.cm-merge-a .cm-changedLineGutter, &.cm-merge-a .cm-deletedLineGutter':{backgroundColor:'var(--danger)'},'&.cm-merge-b .cm-changedLineGutter':{backgroundColor:'var(--success)'},'&.cm-focused':{outline:'none'},'&.cm-merge-a .cm-changedLine':{backgroundColor:'color-mix(in srgb,var(--danger) 10%,transparent)'},'&.cm-merge-b .cm-changedLine':{backgroundColor:'color-mix(in srgb,var(--success) 10%,transparent)'},'.cm-deletedChunk':{backgroundColor:'color-mix(in srgb,var(--danger) 8%,transparent)',backgroundImage:'repeating-linear-gradient(135deg,color-mix(in srgb,var(--danger) 22%,transparent) 0,color-mix(in srgb,var(--danger) 22%,transparent) 1px,transparent 1px,transparent 7px)'},'.cm-insertedLine':{backgroundColor:'color-mix(in srgb,var(--success) 16%,transparent)'},'&.cm-merge-a .cm-changedText':{background:'linear-gradient(color-mix(in srgb,var(--danger) 65%,transparent),color-mix(in srgb,var(--danger) 65%,transparent)) bottom/100% 2px no-repeat'},'&.cm-merge-b .cm-changedText':{background:'linear-gradient(color-mix(in srgb,var(--success) 70%,transparent),color-mix(in srgb,var(--success) 70%,transparent)) bottom/100% 2px no-repeat'}})
function changedLines(chunks:readonly Chunk[],view:MergeView):Counts{let deletions=0,additions=0;for(const chunk of chunks){if(chunk.toA>chunk.fromA)deletions+=view.a.state.doc.lineAt(Math.max(chunk.fromA,chunk.toA-1)).number-view.a.state.doc.lineAt(chunk.fromA).number+1;if(chunk.toB>chunk.fromB)additions+=view.b.state.doc.lineAt(Math.max(chunk.fromB,chunk.toB-1)).number-view.b.state.doc.lineAt(chunk.fromB).number+1}return{deletions,additions}}
function zigSyntax(view:EditorView){const builder=new RangeSetBuilder<Decoration>();const matcher=/\/\/.*|"(?:\\.|[^"\\])*"|@[A-Za-z_]\w*|\b(?:const|var|pub|fn|defer|try|true|false|void)\b|\b(?:i\d+|u\d+|usize|isize|Allocator|ArrayList|GeneralPurposeAllocator)\b|\b\d+\b|[=!+*/<>-]+/gu;for(let lineNo=1;lineNo<=view.state.doc.lines;lineNo++){const line=view.state.doc.line(lineNo);const source=line.text;let match:RegExpExecArray|null;while((match=matcher.exec(source))){const token=match[0];const className=token.startsWith('//')?'cm-zig-comment':token.startsWith('"')?'cm-zig-string':token.startsWith('@')?'cm-zig-builtin':/^(?:const|var|pub|fn|defer|try|true|false|void)$/.test(token)?'cm-zig-keyword':/^(?:i\d+|u\d+|usize|isize|Allocator|ArrayList|GeneralPurposeAllocator)$/.test(token)?'cm-zig-type':/^\d+$/.test(token)?'cm-zig-number':'cm-zig-operator';builder.add(line.from+match.index,line.from+match.index+token.length,Decoration.mark({class:className}))}}return builder.finish()}
const zigHighlight=ViewPlugin.fromClass(class{decorations:DecorationSet;constructor(view:EditorView){this.decorations=zigSyntax(view)}update(update){if(update.docChanged||update.viewportChanged)this.decorations=zigSyntax(update.view)}},{decorations:value=>value.decorations})
function wordRanges(view:EditorView,chunk:Chunk,side:'a'|'b',mode:'word-alt'|'word'){const doc=view.state.doc;const base=side==='a'?chunk.fromA:chunk.fromB;const ranges:Array<[number,number]>=[];for(const change of chunk.changes){const oppositeEmpty=side==='a'?change.fromB===change.toB:change.fromA===change.toA;if(oppositeEmpty)continue;const from=base+(side==='a'?change.fromA:change.fromB);const to=base+(side==='a'?change.toA:change.toB);if(from===to)continue;let line=doc.lineAt(Math.min(from,doc.length));const last=doc.lineAt(Math.min(to,doc.length)).number;while(true){const source=doc.sliceString(line.from,line.to);const matcher=mode==='word-alt'?/\S+/gu:/[\p{L}\p{N}_]+/gu;let match:RegExpExecArray|null;let found=false;while((match=matcher.exec(source))){const start=line.from+match.index;const end=start+match[0].length;if(start<to&&end>from){ranges.push([Math.max(start,from),Math.min(end,to)]);found=true}}if(!found)ranges.push([from,to]);if(line.number===last)break;line=doc.line(line.number+1)}}return ranges.sort((a,b)=>a[0]-b[0]||a[1]-b[1])}
function wordHighlight(mode:'word-alt'|'word'){return ViewPlugin.fromClass(class{decorations:DecorationSet;constructor(view:EditorView){this.decorations=this.build(view)}update(update){if(update.docChanged||update.transactions.length)this.decorations=this.build(update.view)}build(view:EditorView){const info=getChunks(view.state);if(!info)return Decoration.none;const builder=new RangeSetBuilder<Decoration>();for(const chunk of info.chunks)for(const [from,to] of wordRanges(view,chunk,info.side!,mode))if(from<to)builder.add(from,to,Decoration.mark({class:'cm-changedText'}));return builder.finish()}},{decorations:value=>value.decorations})}
function DiffMerge({before,after,theme,mode,revision,onBeforeChange,onAfterChange,onCountsChange}:{before:string;after:string;theme:string;mode:HighlightMode;revision:number;onBeforeChange:(value:string)=>void;onAfterChange:(value:string)=>void;onCountsChange:(counts:Counts)=>void}){const host=useRef<HTMLDivElement>(null);const callbacks=useRef({onBeforeChange,onAfterChange,onCountsChange});callbacks.current={onBeforeChange,onAfterChange,onCountsChange};useEffect(()=>{if(!host.current)return;let merge:MergeView;const refresh=()=>callbacks.current.onCountsChange(changedLines(merge.chunks,merge));const update=(side:'a'|'b')=>EditorView.updateListener.of(update=>{if(!update.docChanged)return;callbacks.current[side==='a'?'onBeforeChange':'onAfterChange'](update.state.doc.toString());queueMicrotask(refresh)});const inline=mode==='character'?[]:mode==='none'?[]:[wordHighlight(mode)];merge=new MergeView({parent:host.current,a:{doc:before,extensions:[minimalSetup,theme==='light'?tokyoNightDay:tokyoNight,diffTheme,zigHighlight,...inline,update('a')]},b:{doc:after,extensions:[minimalSetup,theme==='light'?tokyoNightDay:tokyoNight,diffTheme,zigHighlight,...inline,update('b')]},highlightChanges:mode==='character',gutter:true,diffConfig:{scanLimit:3000,timeout:1000}});const scrollA=merge.a.scrollDOM,scrollB=merge.b.scrollDOM;const sync=(source:HTMLElement,target:HTMLElement)=>{if(target.scrollTop===source.scrollTop&&target.scrollLeft===source.scrollLeft)return;target.scrollTop=source.scrollTop;target.scrollLeft=source.scrollLeft};const onScrollA=()=>sync(scrollA,scrollB);const onScrollB=()=>sync(scrollB,scrollA);scrollA.addEventListener('scroll',onScrollA,{passive:true});scrollB.addEventListener('scroll',onScrollB,{passive:true});refresh();return()=>{scrollA.removeEventListener('scroll',onScrollA);scrollB.removeEventListener('scroll',onScrollB);merge.destroy()}},[revision,theme,mode]);return <div ref={host} className="diff-merge-host min-h-0 min-w-0 overflow-hidden [--wails-draggable:no-drag] select-text"/>}
const highlightModes:HighlightMode[]=['word-alt','word','character','none']
const defaultBefore=`const std = @import("std");
const Allocator = std.heap.page_allocator;
const ArrayList = std.ArrayList;

pub fn main() !void {
    const stdout_writer_instance = std.io.getStdOut().writer();
    try stdout_writer_instance.print("Hi You, {s}! Welcome to our application.\\n", .{"World"});

    var list = ArrayList(i32).init(allocator);
    defer list.deinit();

    const configuration_options = .{ .enable_logging = true, .max_buffer_size = 1024, .timeout_milliseconds = 5000 };
    _ = configuration_options;
}`
export default function DiffTool({active,theme,pending,clearPending}:{active:boolean;theme:string;record?:unknown;pending:PendingAction|null;clearPending:()=>void}){const{t}=useTranslation();const[before,setBefore]=useState(defaultBefore);const[after,setAfter]=useState(defaultAfter);const[mode,setMode]=useState<HighlightMode>('word-alt');const[,setCounts]=useState<Counts>({deletions:0,additions:0});const[revision,setRevision]=useState(0);const consumed=useRef<PendingAction|null>(null);useEffect(()=>{if(!pending||pending===consumed.current||pending.tool!=='diff')return;consumed.current=pending;setBefore(pending.input);setAfter(pending.output??'');setRevision(value=>value+1);clearPending()},[pending,clearPending]);const clear=()=>{setBefore('');setAfter('');setRevision(value=>value+1)};const swap=()=>{setBefore(after);setAfter(before);setRevision(value=>value+1)};const writeSample=()=>{setBefore(defaultBefore);setAfter(defaultAfter);setRevision(value=>value+1)};return <Reveal index={0} fill active={active}><ToolLayout title={t('diffTool.title')} actions={[{key:'highlight',label:t('diffTool.highlightMode'),type:'select',value:mode,options:highlightModes.map(key=>({key,label:t(`diffTool.modes.${key}`)})),onSelect:value=>setMode(value as HighlightMode)}]} className="diff-tool-layout [container-type:inline-size] [&_.tool-heading_h1]:text-sm" contentMode="fixed" footer={<ToolActionBar label={t('diffTool.actions')} actions={[{key:'clear',label:t('diffTool.clear'),icon:Trash,variant:'tertiary',disabled:!before&&!after,onPress:clear},{key:'swap',label:t('diffTool.swap'),icon:ArrowsLeftRight,variant:'secondary',disabled:!before&&!after,onPress:swap},{key:'sample',label:t('diffTool.sample'),icon:FileCode,variant:'primary',onPress:writeSample}]}/>}><div className="diff-tool-content"><DiffMerge before={before} after={after} theme={theme} mode={mode} revision={revision} onBeforeChange={setBefore} onAfterChange={setAfter} onCountsChange={setCounts}/></div></ToolLayout></Reveal>}
const defaultAfter=`const std = @import("std");
const GeneralPurposeAllocator = std.heap.GeneralPurposeAllocator;
const ArrayList = std.ArrayList;

pub fn main() !void {
    var gpa = GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const stdout_writer_instance = std.io.getStdOut().writer();
    try stdout_writer_instance.print("Hello There, {s}! Welcome to the updated Zig application.\\n", .{"Zig"});

    var list = ArrayList(i32).init(allocator);
    defer list.deinit();
    try list.append(42);

    const configuration_options = .{ .enable_logging = true, .max_buffer_size = 2048, .timeout_milliseconds = 10000, .retry_count = 3 };
    _ = configuration_options;
}`
