import {useEffect,useRef,useState} from 'react'
import {basicSetup} from 'codemirror'
import {MergeView,type Chunk} from '@codemirror/merge'
import {EditorView} from '@codemirror/view'
import {tokyoNight} from '@uiw/codemirror-theme-tokyo-night'
import {tokyoNightDay} from '@uiw/codemirror-theme-tokyo-night-day'
import {ArrowsLeftRight,Trash} from '@phosphor-icons/react'
import {useTranslation} from 'react-i18next'
import {Reveal,ToolActionBar,ToolLayout,type PendingAction} from './shared'

type Counts={deletions:number;additions:number}
const diffTheme=EditorView.theme({'&':{height:'auto!important',overflow:'visible!important',font:'11px/1.55 var(--font-mono)',backgroundColor:'var(--surface)'},'.cm-scroller':{height:'auto!important',overflowY:'visible!important',fontFamily:'var(--font-mono)'},'&.cm-focused':{outline:'none'},'&.cm-merge-a .cm-changedLine':{backgroundColor:'color-mix(in srgb,var(--danger) 10%,transparent)'},'&.cm-merge-b .cm-changedLine':{backgroundColor:'color-mix(in srgb,var(--success) 10%,transparent)'},'.cm-deletedChunk':{backgroundColor:'color-mix(in srgb,var(--danger) 16%,transparent)'},'.cm-insertedLine':{backgroundColor:'color-mix(in srgb,var(--success) 16%,transparent)'},'&.cm-merge-a .cm-changedText':{background:'color-mix(in srgb,var(--danger) 24%,transparent)'},'&.cm-merge-b .cm-changedText':{background:'color-mix(in srgb,var(--success) 24%,transparent)'}})
function changedLines(chunks:readonly Chunk[],view:MergeView):Counts{let deletions=0,additions=0;for(const chunk of chunks){if(chunk.toA>chunk.fromA)deletions+=view.a.state.doc.lineAt(Math.max(chunk.fromA,chunk.toA-1)).number-view.a.state.doc.lineAt(chunk.fromA).number+1;if(chunk.toB>chunk.fromB)additions+=view.b.state.doc.lineAt(Math.max(chunk.fromB,chunk.toB-1)).number-view.b.state.doc.lineAt(chunk.fromB).number+1}return{deletions,additions}}
function DiffMerge({before,after,theme,revision,onBeforeChange,onAfterChange,onCountsChange}:{before:string;after:string;theme:string;revision:number;onBeforeChange:(value:string)=>void;onAfterChange:(value:string)=>void;onCountsChange:(counts:Counts)=>void}){const host=useRef<HTMLDivElement>(null);const callbacks=useRef({onBeforeChange,onAfterChange,onCountsChange});callbacks.current={onBeforeChange,onAfterChange,onCountsChange};useEffect(()=>{if(!host.current)return;let merge:MergeView;const refresh=()=>callbacks.current.onCountsChange(changedLines(merge.chunks,merge));const update=(side:'a'|'b')=>EditorView.updateListener.of(update=>{if(!update.docChanged)return;callbacks.current[side==='a'?'onBeforeChange':'onAfterChange'](update.state.doc.toString());queueMicrotask(refresh)});merge=new MergeView({parent:host.current,a:{doc:before,extensions:[basicSetup,theme==='light'?tokyoNightDay:tokyoNight,diffTheme,update('a')]},b:{doc:after,extensions:[basicSetup,theme==='light'?tokyoNightDay:tokyoNight,diffTheme,update('b')]},highlightChanges:true,gutter:true,diffConfig:{scanLimit:3000,timeout:1000}});refresh();return()=>merge.destroy()},[revision,theme]);return <div ref={host} className="min-h-0 min-w-0 overflow-hidden border border-(--border) bg-(--surface) transition-colors focus-within:border-(--muted) [--wails-draggable:no-drag] select-text [&_.cm-mergeView]:h-full [&_.cm-mergeView]:overflow-auto [&_.cm-mergeViewEditors]:min-h-full [&_.cm-mergeViewEditors]:gap-px [&_.cm-mergeViewEditors]:bg-(--border) [&_.cm-mergeViewEditor]:min-w-0 [&_.cm-mergeViewEditor]:bg-(--surface)"/>}
export default function DiffTool({active,theme,pending,clearPending}:{active:boolean;theme:string;record?:unknown;pending:PendingAction|null;clearPending:()=>void}){const{t}=useTranslation();const[before,setBefore]=useState('');const[after,setAfter]=useState('');const[counts,setCounts]=useState<Counts>({deletions:0,additions:0});const[revision,setRevision]=useState(0);const consumed=useRef<PendingAction|null>(null);useEffect(()=>{if(!pending||pending===consumed.current||pending.tool!=='diff')return;consumed.current=pending;setBefore(pending.input);setAfter(pending.output??'');setRevision(value=>value+1);clearPending()},[pending,clearPending]);const clear=()=>{setBefore('');setAfter('');setRevision(value=>value+1)};const swap=()=>{setBefore(after);setAfter(before);setRevision(value=>value+1)};return <Reveal index={0} fill active={active}><ToolLayout title={t('diffTool.title')} className="[container-type:inline-size] [&_.tool-heading_h1]:text-sm" contentMode="fixed" footer={<ToolActionBar label={t('diffTool.actions')} actions={[{key:'clear',label:t('diffTool.clear'),icon:Trash,variant:'tertiary',disabled:!before&&!after,onPress:clear},{key:'swap',label:t('diffTool.swap'),icon:ArrowsLeftRight,variant:'secondary',disabled:!before&&!after,onPress:swap}]}/>}><div className="grid h-full min-h-0 grid-rows-[auto_minmax(0,1fr)] gap-[7px]"><div className="grid grid-cols-2 gap-px font-mono text-[9px] leading-none font-medium tracking-[.05em] text-(--muted) uppercase"><span className="flex items-center justify-between">{t('diffTool.before')}<strong className="text-[10px] leading-none font-semibold text-(--danger)">−{counts.deletions}</strong></span><span className="flex items-center justify-between">{t('diffTool.after')}<strong className="text-[10px] leading-none font-semibold text-(--success)">+{counts.additions}</strong></span></div><DiffMerge before={before} after={after} theme={theme} revision={revision} onBeforeChange={setBefore} onAfterChange={setAfter} onCountsChange={setCounts}/></div></ToolLayout></Reveal>}
