import {useEffect, useRef, useState} from 'react'
import {AlertDialog, Button} from '@heroui/react'
import {BracketsCurly, CaretRight, Clock, FileCode, GitDiff, Hash, TextT, Trash} from '@phosphor-icons/react'
import {useTranslation} from 'react-i18next'
import type {HistoryItem as StoredHistoryItem} from '../../bindings/changeme/models'
import {GetHistoryPage} from '../../bindings/changeme/configservice'
import {Reveal, type ToolId} from './shared'

export type HistoryItem = Omit<StoredHistoryItem,'tool'> & {tool:ToolId}
export function normalizeHistoryDetail(detail:string){return detail.replace(/\s+/g,' ').trim()}
export function toHistoryItem(item:StoredHistoryItem):HistoryItem|null{return item.tool==='json'||item.tool==='time'||item.tool==='text'||item.tool==='base64'||item.tool==='diff'?{...item,tool:item.tool,detail:normalizeHistoryDetail(item.detail)}:null}
export function formatRelative(date:string,t:(k:string,o?:Record<string,unknown>)=>string){const minutes=Math.max(0,Math.round((Date.now()-new Date(date).getTime())/60000));if(minutes<1)return t('timeAgo.justNow');if(minutes<60)return t('timeAgo.minutes',{count:minutes});const hours=Math.round(minutes/60);return hours<24?t('timeAgo.hours',{count:hours}):t('timeAgo.days',{count:Math.round(hours/24)})}
export function HistoryIcon({tool}:{tool:ToolId}){return tool==='json'?<BracketsCurly weight="duotone"/>:tool==='time'?<Clock weight="duotone"/>:tool==='base64'?<FileCode weight="duotone"/>:tool==='diff'?<GitDiff weight="duotone"/>:<TextT weight="duotone"/>}

export function ClearHistoryDialog({open,onClose,onConfirm}:{open:boolean;onClose:()=>void;onConfirm:()=>void}){const{t}=useTranslation();return <AlertDialog.Backdrop isOpen={open} onOpenChange={o=>{if(!o)onClose()}}><AlertDialog.Container><AlertDialog.Dialog className="json-comment-dialog"><AlertDialog.CloseTrigger/><AlertDialog.Header><AlertDialog.Icon status="danger"/><AlertDialog.Heading>{t('clearHistoryDialog.title')}</AlertDialog.Heading></AlertDialog.Header><AlertDialog.Body><p>{t('clearHistoryDialog.body')}</p></AlertDialog.Body><AlertDialog.Footer><Button variant="tertiary" onPress={onClose}>{t('clearHistoryDialog.cancel')}</Button><Button variant="danger" onPress={()=>{onConfirm();onClose()}}>{t('clearHistoryDialog.confirm')}</Button></AlertDialog.Footer></AlertDialog.Dialog></AlertDialog.Container></AlertDialog.Backdrop>}

export default function HistoryPage({openHistory,clear}:{openHistory:(item:HistoryItem)=>void;clear:()=>void}){const{t}=useTranslation();const[confirmClear,setConfirmClear]=useState(false);const[items,setItems]=useState<HistoryItem[]>([]);const[total,setTotal]=useState(0);const[loading,setLoading]=useState(false);const[error,setError]=useState(false);const sentinel=useRef<HTMLDivElement>(null);const loadMore=async()=>{if(loading)return;setLoading(true);try{const page=await GetHistoryPage(items.length,30);setItems(prev=>[...prev,...(page.items??[]).map(toHistoryItem).filter((x):x is HistoryItem=>x!==null)]);setTotal(page.total)}catch{setError(true)}setLoading(false)};useEffect(()=>{void loadMore()},[]);useEffect(()=>{const el=sentinel.current;if(!el||items.length>=total||loading)return;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting)void loadMore()},{rootMargin:'240px'});observer.observe(el);return()=>observer.disconnect()},[items.length,total,loading]);const clearAll=()=>{clear();setItems([]);setTotal(0)};return <Reveal index={0}><section className="history-page"><header className="page-title row"><div><h1>{t('history.title')}</h1><p>{t('history.subtitle')}</p></div>{total>0&&<Button variant="tertiary" onPress={()=>setConfirmClear(true)}><Trash weight="duotone"/>{t('history.clear')}</Button>}</header>{items.length?<div className="history-list">{items.map((item,idx)=><button key={item.id} style={{'--index':idx} as React.CSSProperties} onClick={()=>void openHistory(item)}><span className="history-tool"><HistoryIcon tool={item.tool}/></span><span><strong>{item.action}</strong><small>{item.detail}</small></span><time>{formatRelative(item.at,t)}</time><CaretRight weight="duotone"/></button>)}</div>:error?<button className="empty-state history-empty" onClick={()=>{setError(false);void loadMore()}}><Hash size={28} weight="duotone"/><strong>{t('history.loadFailed')}</strong><span>{t('history.loadFailedHint')}</span></button>:<div className="empty-state history-empty"><Hash size={28} weight="duotone"/><strong>{t('history.emptyTitle')}</strong><span>{t('history.emptyHint')}</span></div>}<div ref={sentinel} className={`history-more${loading||items.length<total?'':' hidden'}`}>{loading?<span className="history-more-spinner" aria-hidden="true"/>:null}</div></section><ClearHistoryDialog open={confirmClear} onClose={()=>setConfirmClear(false)} onConfirm={clearAll}/></Reveal>}
