import {useEffect, useMemo, useRef, useState} from 'react'
import {Button} from '@heroui/react'
import {useTranslation} from 'react-i18next'
import CodeMirror from '@uiw/react-codemirror'
import {json} from '@codemirror/lang-json'
import {vscodeDark} from '@uiw/codemirror-theme-vscode'
import {BracketsCurly, Check, Copy, X} from '@phosphor-icons/react'
import {Reveal, samples, type PendingAction, type ToolId} from './shared'

export default function JsonTool({record,pending,clearPending}:{record:(tool:ToolId,action:string,detail:string)=>void;pending:PendingAction|null;clearPending:()=>void}){
  const{t}=useTranslation();const[input,setInput]=useState(samples.json);const[error,setError]=useState('');const[copied,setCopied]=useState(false);const consumed=useRef<PendingAction|null>(null);const parsed=useMemo(()=>{try{return JSON.parse(input)}catch{return null}},[input]);const stats={bytes:new TextEncoder().encode(input).length,lines:input.split('\n').length}
  useEffect(()=>{if(!pending||consumed.current===pending)return;consumed.current=pending;clearPending();setInput(pending.input);if(pending.action==='validate'){try{JSON.parse(pending.input);setError('');record('json',t('jsonTool.validated'),`${new TextEncoder().encode(pending.input).length} ${t('jsonTool.bytes')}`)}catch(e){setError(e instanceof Error?e.message:t('jsonTool.invalid'))}return}try{const value=JSON.parse(pending.input);setInput(pending.action==='minify'?JSON.stringify(value):JSON.stringify(value,null,2));setError('');record('json',pending.action==='minify'?t('jsonTool.minified'):t('jsonTool.formatted'),`${new TextEncoder().encode(pending.input).length} ${t('jsonTool.bytes')}`)}catch(e){setError(e instanceof Error?e.message:t('jsonTool.invalid'))}},[pending])
  const transform=(minify:boolean)=>{try{const value=JSON.parse(input);setInput(minify?JSON.stringify(value):JSON.stringify(value,null,2));setError('');record('json',minify?t('jsonTool.minified'):t('jsonTool.formatted'),`${stats.bytes} ${t('jsonTool.bytes')}`)}catch(e){setError(e instanceof Error?e.message:t('jsonTool.invalid'))}}
  const copy=async()=>{await navigator.clipboard?.writeText(input);setCopied(true);setTimeout(()=>setCopied(false),1200)}
  return <Reveal index={0} fill><section className="tool-page json-page"><header className="json-toolbar"><span className="json-heading"><span className="tool-heading-icon"><BracketsCurly size={17} weight="bold"/></span><div><h1>{t('jsonTool.title')}</h1><p>{t('jsonTool.subtitle')}</p></div></span></header><div className="json-body"><CodeMirror className="json-cm" height="100%" value={input} onChange={setInput} theme={vscodeDark} extensions={[json()]} placeholder={t('jsonTool.placeholder')}/></div><footer className="json-status"><div className="json-status-left">{error?<span className="json-status-error"><X size={13} weight="bold"/><span>{error}</span></span>:parsed!==null?<span className="json-status-ok"><Check size={13} weight="bold"/><span>{t('jsonTool.valid')}</span><span className="json-status-meta">{stats.bytes.toLocaleString()} {t('jsonTool.bytes')} · {stats.lines} {t('jsonTool.lines')} · {t('jsonTool.rootPath')} $</span></span>:null}</div><div className="tool-actions"><Button variant="primary" onPress={()=>transform(false)}>{t('jsonTool.format')}</Button><Button variant="secondary" onPress={()=>transform(true)}>{t('jsonTool.minify')}</Button><Button variant="secondary" onPress={copy}>{copied?<Check weight="bold"/>:<Copy weight="bold"/>}{copied?t('jsonTool.copied'):t('jsonTool.copy')}</Button></div></footer></section></Reveal>
}
