import {useEffect, useMemo, useRef, useState} from 'react'
import {AlertDialog, Button, ListBox, Select} from '@heroui/react'
import {useTranslation} from 'react-i18next'
import CodeMirror from '@uiw/react-codemirror'
import type {Extension} from '@codemirror/state'
import {json5} from 'codemirror-json5'
import {codeFolding, syntaxTree} from '@codemirror/language'
import {EditorView,keymap} from '@codemirror/view'
import {autocompletion,type CompletionContext,type CompletionResult,acceptCompletion} from '@codemirror/autocomplete'
import {tokyoNight} from '@uiw/codemirror-theme-tokyo-night'
import {tokyoNightDay} from '@uiw/codemirror-theme-tokyo-night-day'
import {ArrowDown,ArrowUp,Check,Copy,CurrencyDollar,DotsSixVertical,Plus,Trash,X} from '@phosphor-icons/react'
import {formatJsonPreserve,hasComments,parseJsonLoose,Reveal,ToolActionBar,ToolLayout,useFocusOnActivate,type PendingAction,type ToolId} from './shared'
import {toast} from './AppToast'

type PathToken={type:'key'|'index'|'all';value:string}
type SourceNode={start:number;end:number;children?:Record<string,SourceNode>|SourceNode[]}
type SortOrder='asc'|'desc'
type SortRule={mode:'key'|'value'|'path';path:string;dir:SortOrder}
function sortJsonByKey(value:unknown,order:SortOrder):unknown{if(Array.isArray(value))return value.map(item=>sortJsonByKey(item,order));if(value!==null&&typeof value==='object'){const object=value as Record<string,unknown>;return Object.keys(object).sort((a,b)=>{const result=a<b?-1:a>b?1:0;return order==='asc'?result:-result}).reduce<Record<string,unknown>>((sorted,key)=>{sorted[key]=sortJsonByKey(object[key],order);return sorted}, {})}return value}
function compareValues(a:unknown,b:unknown):number{const rank=(v:unknown)=>v===null?0:typeof v==='boolean'?1:typeof v==='number'?2:typeof v==='string'?3:4;const ra=rank(a),rb=rank(b);if(ra!==rb)return ra-rb;if(ra<=2)return Number(a)-Number(b);if(ra===3){const sa=String(a),sb=String(b);return sa<sb?-1:sa>sb?1:0}return 0}
function stableSort<T>(arr:T[],key:(x:T,i:number)=>unknown,dir:SortOrder):T[]{const indexed=arr.map((el,i)=>({el,i}));indexed.sort((x,y)=>{const c=compareValues(key(x.el,x.i),key(y.el,y.i));return c!==0?(dir==='asc'?c:-c):x.i-y.i});return indexed.map(x=>x.el)}
function sortJsonByValue(value:unknown,dir:SortOrder):unknown{if(Array.isArray(value)){const next=value.every(el=>el===null||['number','string','boolean'].includes(typeof el))?stableSort(value,v=>v,dir):value;return next.map(el=>sortJsonByValue(el,dir))}if(value!==null&&typeof value==='object'){const object=value as Record<string,unknown>;for(const key of Object.keys(object))object[key]=sortJsonByValue(object[key],dir)}return value}
function sortJsonByPath(value:unknown,path:string,dir:SortOrder):unknown{const tokens=parsePath(path);const walk=(node:unknown,i:number):{ok:true;v:unknown}|{ok:false}=>{let cur:unknown=node;for(let k=i;k<tokens.length;k++){const tok=tokens[k];if(tok.type==='all')return{ok:false};if(tok.type==='index'){if(!Array.isArray(cur))return{ok:false};cur=(cur as unknown[])[Number(tok.value)]}else{if(cur===null||typeof cur!=='object'||Array.isArray(cur)||!(tok.value in cur))return{ok:false};cur=(cur as Record<string,unknown>)[tok.value]}if(cur===undefined)return{ok:false}}return{ok:true,v:cur}};const scalar=(v:unknown)=>v===null||['number','string','boolean'].includes(typeof v);const recurse=(node:any,i:number):any=>{if(Array.isArray(node)){const tok=tokens[i];if(tok&&tok.type==='index'){node[Number(tok.value)]=recurse(node[Number(tok.value)],i+1);return node}if(tok&&tok.type==='all'){const extracted=node.map(el=>walk(el,i+1));if(extracted.every(r=>r.ok&&scalar(r.v)))node=stableSort(node,(el,idx)=>(extracted[idx] as {ok:true;v:unknown}).v,dir);return node.map(el=>recurse(el,i+1))}if(i<tokens.length){const extracted=node.map(el=>walk(el,i));if(extracted.every(r=>r.ok&&scalar(r.v)))node=stableSort(node,(el,idx)=>(extracted[idx] as {ok:true;v:unknown}).v,dir);return node.map(el=>recurse(el,i))}if(node.every(el=>scalar(el)))node=stableSort(node,v=>v,dir);return node.map(el=>recurse(el,i))}if(node!==null&&typeof node==='object'){const object=node as Record<string,unknown>;const tok=tokens[i];if(tok&&tok.type==='all'){for(const key of Object.keys(object))object[key]=recurse(object[key],i+1)}else if(tok&&tok.type==='key')object[tok.value]=recurse(object[tok.value],i+1);else if(tok&&tok.type==='index')return recurse(node,i+1);return node}return node};return recurse(value,0)}
function sourceNode(doc:string,start=0):SourceNode{const skip=(i:number)=>{while(i<doc.length){if(/\s/.test(doc[i])){i++;continue}if(doc[i]==='/'&&doc[i+1]==='/'){i=doc.indexOf('\n',i+2);if(i<0)return doc.length;continue}if(doc[i]==='/'&&doc[i+1]==='*'){i=doc.indexOf('*/',i+2);if(i<0)throw new Error('注释未闭合');i+=2;continue}break}return i};const stringEnd=(i:number)=>{const quote=doc[i++];for(;i<doc.length;i++){if(doc[i]==='\\')i++;else if(doc[i]===quote)return i+1}throw new Error('字符串未闭合')};const value=(i:number):SourceNode=>{i=skip(i);const node:SourceNode={start:i,end:i};if(doc[i]==='{'||doc[i]==='['){const object=doc[i]==='{';const children:Record<string,SourceNode>|SourceNode[]=object?{}:[];i++;while(true){i=skip(i);if(doc[i]===(object?'}':']')){node.end=i+1;break}if(object){if(doc[i]!=='"'&&doc[i]!=="'")throw new Error('对象键无效');const keyStart=i,keyEnd=stringEnd(i),key=JSON.parse(doc.slice(keyStart,keyEnd));i=skip(keyEnd);if(doc[i]!==':')throw new Error('对象键缺少 :');const child=value(i+1);(children as Record<string,SourceNode>)[key]=child;i=skip(child.end)}else{const child=value(i);(children as SourceNode[]).push(child);i=skip(child.end)}if(doc[i]===','){i++;continue}if(doc[i]===(object?'}':']')){node.end=i+1;break}throw new Error('节点未闭合')}node.children=children;return node}if(doc[i]==='"'||doc[i]==="'")node.end=stringEnd(i);else{while(i<doc.length&&!/[\s,}\]]/.test(doc[i]))i++;node.end=i}return node};return value(start)}
function parsePath(p:string):PathToken[]{const tokens:PathToken[]=[];let s=p.trim();if(s.startsWith('$'))s=s.slice(1);let i=0;while(i<s.length){if(s[i]==='.'||s[i]==='/'){i++;continue}if(s[i]==='['){const end=s.indexOf(']',i);if(end<0)throw new Error('路径缺少 ]');const inner=s.slice(i+1,end).trim();if(inner==='*')tokens.push({type:'all',value:'*'});else if(/^-?\d+$/.test(inner))tokens.push({type:'index',value:inner});else if((inner.startsWith("'")&&inner.endsWith("'"))||(inner.startsWith('"')&&inner.endsWith('"')))tokens.push({type:'key',value:inner.slice(1,-1)});else throw new Error('路径段无效: '+inner);i=end+1}else if(/[A-Za-z0-9_$]/.test(s[i])){let j=i;while(j<s.length&&/[A-Za-z0-9_$-]/.test(s[j]))j++;tokens.push({type:'key',value:s.slice(i,j)});i=j}else throw new Error('路径字符无效: '+s[i])}return tokens}
function splitPathSegments(prefix:string){const tokens:PathToken[]=[];let s=prefix;if(s.startsWith('$'))s=s.slice(1);let i=0,partial='',inBracket=false,followedBySep=false;const len=s.length;while(i<len){const ch=s[i];if(ch==='.'||ch===' '||ch==='/'){i++;continue}if(ch==='['){const end=s.indexOf(']',i);if(end<0){inBracket=true;partial=s.slice(i+1);break}const inner=s.slice(i+1,end).trim();if(inner==='*')tokens.push({type:'all',value:'*'});else if(/^-?\d+$/.test(inner))tokens.push({type:'index',value:inner});else if((inner.startsWith("'")&&inner.endsWith("'"))||(inner.startsWith('"')&&inner.endsWith('"')))tokens.push({type:'key',value:inner.slice(1,-1)});else{inBracket=true;partial=inner;break}i=end+1;followedBySep=i<len&&(s[i]==='.'||s[i]==='/')}else if(/[A-Za-z0-9_$]/.test(ch)){let j=i;while(j<len&&/[A-Za-z0-9_$-]/.test(s[j]))j++;if(j>=len){partial=s.slice(i);break}tokens.push({type:'key',value:s.slice(i,j)});i=j}else i++}return{tokens,partial,inBracket,followedBySep}}
function pathCompletions(root:any){const source=(context:CompletionContext):CompletionResult|null=>{const prefix=context.state.doc.sliceString(0,context.pos).replace(/\s+$/,'');const{tokens,partial,inBracket,followedBySep}=splitPathSegments(prefix);let node:any=root;for(let i=0;i<tokens.length;i++){const tok=tokens[i];if(tok.type==='all'){if(i===tokens.length-1){node=Array.isArray(node)?node:(node&&typeof node==='object'?Object.values(node):undefined);if(!Array.isArray(node))return null;if(followedBySep&&!inBracket)node=node[0]}else return null}else if(tok.type==='index'){if(!Array.isArray(node))return null;node=node[Number(tok.value)]}else{if(node==null||typeof node!=='object')return null;node=node[tok.value]}if(node===undefined)return null}if(node==null||typeof node!=='object')return null;const filter=partial.trim().toLowerCase().replace(/[^a-z0-9_$]/g,'');const end=context.pos+(context.state.doc.sliceString(context.pos,context.pos+1)===']'?1:0);const from=inBracket?context.pos-partial.length-1:(partial.length?context.pos-partial.length:context.pos);if(Array.isArray(node)){if(!inBracket)return null;const options=node.map((_,i)=>({label:`[${i}]`,apply:`[${i}]`,type:'keyword'})).concat({label:'[*]',apply:'[*]',type:'keyword'}).filter(o=>!filter||o.label.slice(1,-1).toLowerCase().startsWith(filter));return{from,to:end,options,validFor:/[^\]'"]*/}}const keys=Object.keys(node);const options=inBracket?keys.map(k=>({label:`['${k}']`,apply:`['${k}']`,type:'property'})):keys.map(k=>({label:k,apply:k,type:'property'}));const filtered=options.filter(o=>!filter||o.label.toLowerCase().replace(/[^a-z0-9_$]/g,'').startsWith(filter));if(!filtered.length)return null;return{from,to:end,options:filtered,validFor:inBracket?/[^\]'"]*/:/[A-Za-z0-9_$-]*/}};return autocompletion({override:[source]})}
function matchPath(doc:string,path:string):{ok:true;value:unknown;source?:string}|{ok:false;error:string}{try{const root=parseJsonLoose(doc);const tokens=parsePath(path);const walk=(cur:any,i:number):any=>{if(i>=tokens.length)return cur;const tok=tokens[i];if(tok.type==='all'){const children=Array.isArray(cur)?cur:(cur&&typeof cur==='object'?Object.values(cur):[]);return children.map(c=>walk(c,i+1))}if(tok.type==='index'){if(!Array.isArray(cur))throw new Error('该位置不是数组');const next=cur[Number(tok.value)];if(next===undefined)throw new Error('数组下标越界');return walk(next,i+1)}if(cur==null||typeof cur!=='object')throw new Error('该位置没有键 '+tok.value);if(!(tok.value in cur))throw new Error('找不到键 '+tok.value);return walk(cur[tok.value],i+1)};const value=walk(root,0);let node=sourceNode(doc);for(const token of tokens){if(token.type==='all'){node=undefined as never;break}const children=node.children;if(token.type==='index'){if(!Array.isArray(children))throw new Error('该位置不是数组');node=children[Number(token.value)]}else{if(!children||Array.isArray(children))throw new Error('该位置没有键 '+token.value);node=children[token.value]}if(!node)throw new Error('路径未找到')}return{ok:true,value,source:node?doc.slice(node.start,node.end):undefined}}catch(e){return{ok:false,error:e instanceof Error?e.message:String(e)}}}

function JsonEditorPane({value,onChange,foldExt,onCreate,theme}:{value:string;onChange:(v:string)=>void;foldExt:ReturnType<typeof codeFolding>;onCreate?:(v:EditorView)=>void;theme:Extension}){
  return <div className="json-pane"><div className="json-pane-editor"><CodeMirror className="json-cm" height="100%" value={value} onChange={onChange} onCreateEditor={onCreate} theme={theme} extensions={[json5(),foldExt]}/></div></div>
}

function SortRuleSelect({label,value,options,onSelect,className=''}:{label:string;value:string;options:Array<{key:string;label:string}>;onSelect:(v:string)=>void;className?:string}){return <Select className={`json-sort-select ${className}`.trim()} selectedKey={value} aria-label={label} onSelectionChange={key=>{if(key!=null)onSelect(String(key))}}><Select.Trigger><Select.Value/><Select.Indicator/></Select.Trigger><Select.Popover><ListBox>{options.map(option=><ListBox.Item key={option.key} id={option.key} textValue={option.label}>{option.label}</ListBox.Item>)}</ListBox></Select.Popover></Select>}

function SortPanel({rules,onChange,onRemove,onMove,onAdd,canApply,onApply,canRestore,onRestore}:{rules:SortRule[];onChange:(i:number,patch:Partial<SortRule>)=>void;onRemove:(i:number)=>void;onMove:(from:number,to:number)=>void;onAdd:()=>void;canApply:boolean;onApply:()=>void;canRestore:boolean;onRestore:()=>void}){
  const{t}=useTranslation();const[drag,setDrag]=useState<number|null>(null);const lastOver=useRef<number|null>(null)
  const modeOptions=[{key:'key',label:t('jsonTool.sortByKey')},{key:'value',label:t('jsonTool.sortByValue')}];const dirOptions=[{key:'asc',label:t('jsonTool.sortOrderAsc')},{key:'desc',label:t('jsonTool.sortOrderDesc')}]
  return <div className="json-sort-panel"><div className="json-sort-header"><span>{t('jsonTool.sortRules')}</span><div className="json-sort-header-actions">{canRestore&&<Button variant="secondary" className="json-sort-restore" onPress={onRestore}>{t('jsonTool.sortRestore')}</Button>}<Button variant="secondary" className="json-sort-add" onPress={onAdd}><Plus size={12} weight="duotone"/>{t('jsonTool.sortAddRule')}</Button></div></div><div className="json-sort-list">{rules.map((rule,i)=>{const isPath=rule.mode==='path';return <div key={i} className={`json-sort-rule${drag===i?' dragging':''}`} onDragOver={e=>e.preventDefault()} onDragEnter={e=>{if(drag!==null&&drag!==i&&i!==lastOver.current){lastOver.current=i;onMove(drag,i);setDrag(i)}}}><button className="json-sort-drag-handle" draggable onDragStart={e=>{setDrag(i);lastOver.current=null;e.dataTransfer.setData('text/plain','');e.dataTransfer.effectAllowed='move'}} onDragEnd={()=>{setDrag(null);lastOver.current=null}} aria-label={t('jsonTool.sortDrag')} title={t('jsonTool.sortDrag')}><DotsSixVertical size={14} weight="duotone"/></button>{isPath?<input className="json-sort-path-input" value={rule.path} placeholder={t('jsonTool.sortPathPlaceholder')} spellCheck={false} onChange={e=>onChange(i,{path:e.target.value})}/>:<SortRuleSelect label={t('jsonTool.sortTarget')} value={rule.mode} options={modeOptions} onSelect={v=>onChange(i,{mode:v as SortRule['mode']})}/>}<button className="json-sort-dollar" onClick={()=>onChange(i,isPath?{mode:'key'}:{mode:'path'})} aria-label={t('jsonTool.sortPathToggle')} title={t('jsonTool.sortPathToggle')}><CurrencyDollar size={14} weight="duotone"/></button><SortRuleSelect className="dir" label={t('jsonTool.sortDirection')} value={rule.dir} options={dirOptions} onSelect={v=>onChange(i,{dir:v as SortOrder})}/><button className="json-sort-move" disabled={i===0} onClick={()=>onMove(i,i-1)} aria-label={t('jsonTool.sortMoveUp')} title={t('jsonTool.sortMoveUp')}><ArrowUp size={13} weight="duotone"/></button><button className="json-sort-move" disabled={i===rules.length-1} onClick={()=>onMove(i,i+1)} aria-label={t('jsonTool.sortMoveDown')} title={t('jsonTool.sortMoveDown')}><ArrowDown size={13} weight="duotone"/></button><button className="json-sort-delete" onClick={()=>onRemove(i)} aria-label={t('jsonTool.sortDelete')} title={t('jsonTool.sortDelete')}><X size={13} weight="duotone"/></button></div>})}</div><footer className="json-sort-footer"><Button variant="primary" className="json-sort-apply" isDisabled={!canApply} onPress={onApply}>{t('jsonTool.sortApply')}</Button></footer></div>
}

export default function JsonTool({active,theme,record,pending,clearPending}:{active:boolean;theme:string;record:(tool:ToolId,action:string,detail:string,input:string)=>void;pending:PendingAction|null;clearPending:()=>void}){
  const{t}=useTranslation();const[schema,setSchema]=useState(false);const[sortMode,setSortMode]=useState(false);const[input,setInput]=useState('');const[path,setPath]=useState('$');const[result,setResult]=useState('');const[pathError,setPathError]=useState('');const[sortRules,setSortRules]=useState<SortRule[]>([{mode:'key',path:'',dir:'asc'}]);const[sortSource,setSortSource]=useState<string|null>(null);const[copiedPane,setCopiedPane]=useState<'input'|'result'|null>(null);const[commentDialog,setCommentDialog]=useState<null|{mode:'format'|'minify';pane:'input'|'result'}>(null);const consumed=useRef<PendingAction|null>(null);const copyTimer=useRef<number|null>(null);const views=useRef(new Map<string,EditorView>());useFocusOnActivate(active,()=>views.current.get('input')?.focus())
  const cmTheme=theme==='light'?tokyoNightDay:tokyoNight
  const jsonValue=useMemo(()=>{try{return parseJsonLoose(input)}catch{return null}},[input])
  const pathExt=useMemo(()=>[EditorView.lineWrapping,jsonValue?pathCompletions(jsonValue):autocompletion({override:[]}),keymap.of([{key:'Tab',run:v=>{acceptCompletion(v);return true}}])],[jsonValue])
  const foldExt=useMemo(()=>codeFolding({
    preparePlaceholder:(state:any,range:{from:number;to:number})=>{let node=syntaxTree(state).resolveInner(range.from,1);while(node&&node.name!=='Object'&&node.name!=='Array'&&node.parent)node=node.parent;if(!node)return'…';if(node.name==='Object')return t('jsonTool.foldObject',{count:node.getChildren('Property').length});let n=0;const c=node.cursor();if(c.firstChild())do{if(!['[',']',','].includes(c.name))n++}while(c.nextSibling());return t('jsonTool.foldArray',{count:n})},
    placeholderDOM:(_view:unknown,onclick:(e:Event)=>void,prepared?:string)=>{const el=document.createElement('span');el.textContent=prepared??'…';el.className='cm-foldPlaceholder';el.onclick=onclick;return el},
  }),[t])
  const runTransform=(pane:'input'|'result',minify:boolean,stripComments:boolean)=>{const src=pane==='input'?input:result;const set=pane==='input'?setInput:setResult;try{let next;if(!minify&&!stripComments&&hasComments(src)){next=formatJsonPreserve(src);try{parseJsonLoose(next)}catch{toast(t('jsonTool.formatFailed'),{description:t('jsonTool.invalidJsonDesc'),variant:'danger'});return}}else{const v=stripComments?parseJsonLoose(src):JSON.parse(src);next=minify?JSON.stringify(v):JSON.stringify(v,null,2)}set(next);record('json',minify?t('jsonTool.minified'):t('jsonTool.formatted'),next,next)}catch{toast(t(minify?'jsonTool.minifyFailed':'jsonTool.formatFailed'),{description:t('jsonTool.invalidJsonDesc'),variant:'danger'})}}
  const requestTransform=(pane:'input'|'result',minify:boolean)=>{if(hasComments(pane==='input'?input:result))setCommentDialog({mode:minify?'minify':'format',pane});else runTransform(pane,minify,false)}
  const changeInput=(value:string)=>{setInput(value);if(sortSource!==null)setSortSource(null)}
  const toggleSchema=()=>{setSchema(v=>{const next=!v;if(next)setSortMode(false);return next})}
  const toggleSort=()=>{setSortMode(v=>{const next=!v;if(next)setSchema(false);return next})}
  const addRule=()=>setSortRules(r=>[...r,{mode:'key',path:'',dir:'asc'}])
  const updateRule=(index:number,patch:Partial<SortRule>)=>setSortRules(r=>r.map((rule,i)=>i===index?{...rule,...patch}:rule))
  const removeRule=(index:number)=>setSortRules(r=>r.filter((_,i)=>i!==index))
  const moveRule=(from:number,to:number)=>{if(from===to||to<0||to>=sortRules.length)return;setSortRules(r=>{const next=[...r];const[moved]=next.splice(from,1);next.splice(to,0,moved);return next})}
  const applySort=()=>{if(!sortRules.length)return;const source=sortSource??input;try{const root=parseJsonLoose(source);const before=JSON.stringify(root);let value:unknown=root;for(const rule of sortRules){if(rule.mode==='key')value=sortJsonByKey(value,rule.dir);else if(rule.mode==='value')value=sortJsonByValue(value,rule.dir);else{if(!rule.path.trim())throw new Error(t('jsonTool.sortPathRequired'));value=sortJsonByPath(value,rule.path,rule.dir)}}const formatted=JSON.stringify(value,null,2);if(JSON.stringify(value)===before){toast(t('jsonTool.sortNothingMatched'),{variant:'warning'});return}if(sortSource===null)setSortSource(source);setInput(formatted);record('json',t('jsonTool.sorted'),formatted,source)}catch(e){toast(t('jsonTool.sortFailed'),{description:e instanceof Error?e.message:String(e),variant:'danger'})}}
  const restoreSort=()=>{if(sortSource===null)return;setInput(sortSource);setSortSource(null)}
  const copyPane=async(pane:'input'|'result')=>{const value=pane==='input'?input:result;await navigator.clipboard?.writeText(value);setCopiedPane(pane);if(copyTimer.current!==null)window.clearTimeout(copyTimer.current);copyTimer.current=window.setTimeout(()=>setCopiedPane(null),1200)}
  const editorActions=(pane:'input'|'result')=>{const value=pane==='input'?input:result;const copied=copiedPane===pane;return <ToolActionBar label={t(pane==='input'?'jsonTool.inputActions':'jsonTool.resultActions')} actions={[{key:'clear',label:t('jsonTool.clear'),icon:Trash,variant:'tertiary',disabled:!value,onPress:()=>pane==='input'?changeInput(''):setResult('')},{key:'copy',label:copied?t('jsonTool.copied'):t('jsonTool.copy'),icon:copied?Check:Copy,variant:'secondary',disabled:!value,onPress:()=>copyPane(pane)},{key:'minify',label:t('jsonTool.minify'),variant:'secondary',disabled:!value,onPress:()=>requestTransform(pane,true)},{key:'format',label:t('jsonTool.format'),variant:'primary',disabled:!value,onPress:()=>requestTransform(pane,false)}]}/>}
  useEffect(()=>()=>{if(copyTimer.current!==null)window.clearTimeout(copyTimer.current)},[])
  useEffect(()=>{if(!pending||pending.tool!=='json'||consumed.current===pending)return;consumed.current=pending;clearPending();if(pending.action==='schema'){toggleSchema();return}if(pending.action==='sort'){toggleSort();return}if(pending.action==='sortDefault'){restoreSort();return}if(pending.action==='copy'){const toCopy=input.trim()||pending.input;if(!toCopy.trim()){toast(t('toast.clipboardEmpty'),{description:t('toast.clipboardEmptyDesc'),variant:'warning'});return}void navigator.clipboard?.writeText(toCopy).catch(()=>{});setCopiedPane('input');if(copyTimer.current!==null)window.clearTimeout(copyTimer.current);copyTimer.current=window.setTimeout(()=>setCopiedPane(null),1200);const bytes=new TextEncoder().encode(toCopy).length;toast(t('toast.copied',{value:`${bytes} ${t('jsonTool.bytes')}`}));record('json',t('jsonTool.copied'),`${bytes} ${t('jsonTool.bytes')}`,toCopy);return}changeInput(pending.input);if(pending.action==='restore')return;if(pending.action==='validate'){try{JSON.parse(pending.input);record('json',t('jsonTool.validated'),pending.input,pending.input)}catch{record('json',t('jsonTool.invalid'),pending.input,pending.input)}return}try{const v=JSON.parse(pending.input);const next=pending.action==='minify'?JSON.stringify(v):JSON.stringify(v,null,2);changeInput(next);record('json',pending.action==='minify'?t('jsonTool.minified'):t('jsonTool.formatted'),next,next)}catch{record('json',t('jsonTool.invalid'),pending.input,pending.input)}},[pending])
  useEffect(()=>{if(!schema)return;const m=matchPath(input,path);if(m.ok)setResult(m.source??JSON.stringify(m.value,null,2));setPathError(m.ok?'':m.error)},[schema,input,path])
  useEffect(()=>{for(const v of views.current.values())v.requestMeasure();const timer=window.setTimeout(()=>views.current.get(schema?'path':'input')?.focus(),0);return()=>window.clearTimeout(timer)},[schema,sortMode])
  return <Reveal index={0} fill active={active}><ToolLayout title={t('jsonTool.title')} desc={t('jsonTool.subtitle')} actions={[{key:'schema',label:t('jsonTool.schema'),type:'toggle',checked:schema,onPress:toggleSchema},{key:'sort',label:t('jsonTool.sortRules'),type:'toggle',checked:sortMode,onPress:toggleSort}]} className="json-page" contentMode="fixed" footer={<div className={`json-footer-actions${schema?'':' single'}`}>{editorActions('input')}{schema&&editorActions('result')}</div>}><div className={`json-schema-layout${schema||sortMode?'':' single'}`}><JsonEditorPane value={input} onChange={changeInput} foldExt={foldExt} onCreate={v=>views.current.set('input',v)} theme={cmTheme}/><div className={`json-schema-right${schema?'':' hidden'}`}><div className="json-path"><div className="json-path-field"><CodeMirror className="json-cm json-path-cm" height="100%" value={path} onChange={setPath} theme={cmTheme} indentWithTab={false} onCreateEditor={v=>views.current.set('path',v)} basicSetup={{lineNumbers:false,foldGutter:false,autocompletion:false,closeBrackets:false}} extensions={pathExt} placeholder={t('jsonTool.schemaPathPlaceholder')}/></div>{pathError?<span className="json-path-error"><X size={12} weight="duotone"/><span>{pathError}</span></span>:null}</div><JsonEditorPane value={result} onChange={setResult} foldExt={foldExt} onCreate={v=>views.current.set('result',v)} theme={cmTheme}/></div>{sortMode&&<SortPanel rules={sortRules} onChange={updateRule} onRemove={removeRule} onMove={moveRule} onAdd={addRule} canApply={!!input&&sortRules.length>0} onApply={applySort} canRestore={sortSource!==null} onRestore={restoreSort}/>}</div></ToolLayout><AlertDialog.Backdrop isOpen={commentDialog!==null} onOpenChange={open=>{if(!open)setCommentDialog(null)}}><AlertDialog.Container><AlertDialog.Dialog className="json-comment-dialog"><AlertDialog.CloseTrigger/><AlertDialog.Header><AlertDialog.Icon status="warning"/><AlertDialog.Heading>{t('jsonTool.commentTitle')}</AlertDialog.Heading></AlertDialog.Header><AlertDialog.Body><p>{commentDialog?.mode==='minify'?t('jsonTool.commentMinifyBody'):t('jsonTool.commentFormatBody')}</p></AlertDialog.Body><AlertDialog.Footer><Button variant="tertiary" onPress={()=>setCommentDialog(null)}>{t('jsonTool.cancel')}</Button>{commentDialog?.mode==='format'&&<Button variant="secondary" onPress={()=>{const d=commentDialog;setCommentDialog(null);if(d)runTransform(d.pane,false,false)}}>{t('jsonTool.keepComments')}</Button>}<Button variant="primary" onPress={()=>{const d=commentDialog;setCommentDialog(null);if(d)runTransform(d.pane,d.mode==='minify',true)}}>{commentDialog?.mode==='minify'?t('jsonTool.minifyClear'):t('jsonTool.clearComments')}</Button></AlertDialog.Footer></AlertDialog.Dialog></AlertDialog.Container></AlertDialog.Backdrop></Reveal>
}
