import {useEffect, useMemo, useRef, useState} from 'react'
import {Button} from '@heroui/react'
import {useTranslation} from 'react-i18next'
import CodeMirror from '@uiw/react-codemirror'
import {json} from '@codemirror/lang-json'
import {codeFolding, syntaxTree} from '@codemirror/language'
import {EditorView} from '@codemirror/view'
import {autocompletion, type CompletionContext, type CompletionResult} from '@codemirror/autocomplete'
import {vscodeDark} from '@uiw/codemirror-theme-vscode'
import {BracketsCurly, Check, Copy, Path, X} from '@phosphor-icons/react'
import {Reveal, samples, type PendingAction, type ToolId} from './shared'

type PathToken={type:'key'|'index'|'all';value:string}
function parsePath(p:string):PathToken[]{const tokens:PathToken[]=[];let s=p.trim();if(s.startsWith('$'))s=s.slice(1);let i=0;while(i<s.length){if(s[i]==='.'||s[i]==='/'){i++;continue}if(s[i]==='['){const end=s.indexOf(']',i);if(end<0)throw new Error('路径缺少 ]');const inner=s.slice(i+1,end).trim();if(inner==='*')tokens.push({type:'all',value:'*'});else if(/^-?\d+$/.test(inner))tokens.push({type:'index',value:inner});else if((inner.startsWith("'")&&inner.endsWith("'"))||(inner.startsWith('"')&&inner.endsWith('"')))tokens.push({type:'key',value:inner.slice(1,-1)});else throw new Error('路径段无效: '+inner);i=end+1}else if(/[A-Za-z0-9_$]/.test(s[i])){let j=i;while(j<s.length&&/[A-Za-z0-9_$-]/.test(s[j]))j++;tokens.push({type:'key',value:s.slice(i,j)});i=j}else throw new Error('路径字符无效: '+s[i])}return tokens}
function splitPathSegments(prefix:string){const tokens:PathToken[]=[];let s=prefix;if(s.startsWith('$'))s=s.slice(1);let i=0,partial='',inBracket=false;const len=s.length;while(i<len){const ch=s[i];if(ch==='.'||ch===' '||ch==='/'){i++;continue}if(ch==='['){const end=s.indexOf(']',i);if(end<0){inBracket=true;partial=s.slice(i+1);break}const inner=s.slice(i+1,end).trim();if(inner==='*')tokens.push({type:'all',value:'*'});else if(/^-?\d+$/.test(inner))tokens.push({type:'index',value:inner});else if((inner.startsWith("'")&&inner.endsWith("'"))||(inner.startsWith('"')&&inner.endsWith('"')))tokens.push({type:'key',value:inner.slice(1,-1)});else{inBracket=true;partial=inner;break}i=end+1}else if(/[A-Za-z0-9_$]/.test(ch)){let j=i;while(j<len&&/[A-Za-z0-9_$-]/.test(s[j]))j++;if(j>=len){partial=s.slice(i);break}tokens.push({type:'key',value:s.slice(i,j)});i=j}else i++}return{tokens,partial,inBracket}}
function pathCompletions(root:any){const source=(context:CompletionContext):CompletionResult|null=>{const prefix=context.state.doc.sliceString(0,context.pos).replace(/\s+$/,'');const{tokens,partial,inBracket}=splitPathSegments(prefix);let node:any=root;for(let i=0;i<tokens.length;i++){const tok=tokens[i];if(tok.type==='all'){if(i===tokens.length-1){node=Array.isArray(node)?node:(node&&typeof node==='object'?Object.values(node):undefined);if(!Array.isArray(node))return null}else return null}else if(tok.type==='index'){if(!Array.isArray(node))return null;node=node[Number(tok.value)]}else{if(node==null||typeof node!=='object')return null;node=node[tok.value]}if(node===undefined)return null}if(node==null||typeof node!=='object')return null;const filter=partial.trim().toLowerCase().replace(/[^a-z0-9_$]/g,'');if(Array.isArray(node)){if(!inBracket)return null;const options=node.map((_,i)=>({label:`[${i}]`,apply:`${i}]`,type:'keyword'})).concat({label:'[*]',apply:'*]',type:'keyword'}).filter(o=>!filter||o.label.slice(1,-1).toLowerCase().startsWith(filter));return{from:partial.length?context.pos-partial.length:context.pos-1,to:context.pos,options,validFor:/[^\]'"]*/}}const keys=Object.keys(node);const options=inBracket?keys.map(k=>({label:`['${k}']`,apply:`'${k}']`,type:'property'})):keys.map(k=>({label:k,apply:k,type:'property'}));const filtered=options.filter(o=>!filter||o.label.toLowerCase().replace(/[^a-z0-9_$]/g,'').startsWith(filter));if(!filtered.length)return null;const from=inBracket?(partial.length?context.pos-partial.length:context.pos-1):(partial.length?context.pos-partial.length:context.pos);return{from,to:context.pos,options:filtered,validFor:inBracket?/[^\]'"]*/:/[A-Za-z0-9_$-]*/}};return autocompletion({override:[source]})}
function matchPath(doc:string,path:string):{ok:true;value:unknown}|{ok:false;error:string}{try{const root=JSON.parse(doc);const tokens=parsePath(path);const walk=(cur:any,i:number):any=>{if(i>=tokens.length)return cur;const tok=tokens[i];if(tok.type==='all'){const children=Array.isArray(cur)?cur:(cur&&typeof cur==='object'?Object.values(cur):[]);return children.map(c=>walk(c,i+1))}if(tok.type==='index'){if(!Array.isArray(cur))throw new Error('该位置不是数组');const next=cur[Number(tok.value)];if(next===undefined)throw new Error('数组下标越界');return walk(next,i+1)}if(cur==null||typeof cur!=='object')throw new Error('该位置没有键 '+tok.value);if(!(tok.value in cur))throw new Error('找不到键 '+tok.value);return walk(cur[tok.value],i+1)};return{ok:true,value:walk(root,0)}}catch(e){return{ok:false,error:e instanceof Error?e.message:String(e)}}}

function JsonEditorPane({value,onChange,record,placeholder,foldExt}:{value:string;onChange:(v:string)=>void;record:(tool:ToolId,action:string,detail:string)=>void;placeholder:string;foldExt:ReturnType<typeof codeFolding>}){
  const{t}=useTranslation();const[copied,setCopied]=useState(false);const bytes=new TextEncoder().encode(value).length
  const transform=(minify:boolean)=>{try{const v=JSON.parse(value);onChange(minify?JSON.stringify(v):JSON.stringify(v,null,2));record('json',minify?t('jsonTool.minified'):t('jsonTool.formatted'),`${bytes} ${t('jsonTool.bytes')}`)}catch{}}
  const copy=async()=>{await navigator.clipboard?.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1200)}
  return <div className="json-pane"><div className="json-pane-editor"><CodeMirror className="json-cm" height="100%" value={value} onChange={onChange} theme={vscodeDark} extensions={[json(),foldExt]} placeholder={placeholder}/></div><footer className="json-status"><div className="tool-actions"><Button variant="primary" onPress={()=>transform(false)}>{t('jsonTool.format')}</Button><Button variant="secondary" onPress={()=>transform(true)}>{t('jsonTool.minify')}</Button><Button variant="secondary" onPress={copy}>{copied?<Check weight="bold"/>:<Copy weight="bold"/>}{copied?t('jsonTool.copied'):t('jsonTool.copy')}</Button></div></footer></div>
}

export default function JsonTool({record,pending,clearPending}:{record:(tool:ToolId,action:string,detail:string)=>void;pending:PendingAction|null;clearPending:()=>void}){
  const{t}=useTranslation();const[schema,setSchema]=useState(false);const[input,setInput]=useState(samples.json);const[path,setPath]=useState('$');const[result,setResult]=useState('');const[pathError,setPathError]=useState('');const consumed=useRef<PendingAction|null>(null)
  const jsonValue=useMemo(()=>{try{return JSON.parse(input)}catch{return null}},[input])
  const pathExt=useMemo(()=>[EditorView.lineWrapping,jsonValue?pathCompletions(jsonValue):autocompletion({override:[]})],[jsonValue])
  const foldExt=useMemo(()=>codeFolding({
    preparePlaceholder:(state:any,range:{from:number;to:number})=>{let node=syntaxTree(state).resolveInner(range.from,1);while(node&&node.name!=='Object'&&node.name!=='Array'&&node.parent)node=node.parent;if(!node)return'…';if(node.name==='Object')return t('jsonTool.foldObject',{count:node.getChildren('Property').length});let n=0;const c=node.cursor();if(c.firstChild())do{if(!['[',']',','].includes(c.name))n++}while(c.nextSibling());return t('jsonTool.foldArray',{count:n})},
    placeholderDOM:(_view:unknown,onclick:(e:Event)=>void,prepared?:string)=>{const el=document.createElement('span');el.textContent=prepared??'…';el.className='cm-foldPlaceholder';el.onclick=onclick;return el},
  }),[t])
  useEffect(()=>{if(!pending||consumed.current===pending)return;consumed.current=pending;clearPending();setInput(pending.input);if(pending.action==='validate'){try{JSON.parse(pending.input);record('json',t('jsonTool.validated'),`${new TextEncoder().encode(pending.input).length} ${t('jsonTool.bytes')}`)}catch(e){record('json',t('jsonTool.invalid'),e instanceof Error?e.message:t('jsonTool.invalid'))}return}try{const v=JSON.parse(pending.input);setInput(pending.action==='minify'?JSON.stringify(v):JSON.stringify(v,null,2));record('json',pending.action==='minify'?t('jsonTool.minified'):t('jsonTool.formatted'),`${new TextEncoder().encode(pending.input).length} ${t('jsonTool.bytes')}`)}catch(e){record('json',t('jsonTool.invalid'),e instanceof Error?e.message:t('jsonTool.invalid'))}},[pending])
  useEffect(()=>{if(!schema)return;const m=matchPath(input,path);if(m.ok)setResult(JSON.stringify(m.value,null,2));setPathError(m.ok?'':m.error)},[schema,input,path])
  return <Reveal index={0} fill><section className="tool-page json-page"><header className="json-toolbar"><span className="json-heading"><span className="tool-heading-icon"><BracketsCurly size={17} weight="bold"/></span><div><h1>{t('jsonTool.title')}</h1><p>{t('jsonTool.subtitle')}</p></div></span><button className={`schema-toggle${schema?' active':''}`} aria-pressed={schema} onClick={()=>setSchema(v=>!v)}><Path size={14} weight="bold"/>{t('jsonTool.schema')}</button></header>{schema?<div className="json-schema-layout"><JsonEditorPane value={input} onChange={setInput} record={record} placeholder={t('jsonTool.placeholder')} foldExt={foldExt}/><div className="json-schema-right"><div className="json-path"><span className="json-path-label">{t('jsonTool.schemaPathLabel')}</span><div className="json-path-field"><CodeMirror className="json-cm json-path-cm" height="100%" value={path} onChange={setPath} theme={vscodeDark} basicSetup={{lineNumbers:false,foldGutter:false,autocompletion:false}} extensions={pathExt} placeholder={t('jsonTool.schemaPathPlaceholder')}/></div>{pathError?<span className="json-path-error"><X size={12} weight="bold"/><span>{pathError}</span></span>:null}</div><JsonEditorPane value={result} onChange={setResult} record={record} placeholder={t('jsonTool.placeholder')} foldExt={foldExt}/></div></div>:<JsonEditorPane value={input} onChange={setInput} record={record} placeholder={t('jsonTool.placeholder')} foldExt={foldExt}/>}</section></Reveal>
}
