import {useEffect,useMemo,useRef,useState} from 'react'
import {Check,Copy,Trash} from '@phosphor-icons/react'
import {useTranslation} from 'react-i18next'
import CodeMirror from '@uiw/react-codemirror'
import {EditorView} from '@codemirror/view'
import {json} from '@codemirror/lang-json'
import {tokyoNight} from '@uiw/codemirror-theme-tokyo-night'
import {tokyoNightDay} from '@uiw/codemirror-theme-tokyo-night-day'
import {Reveal,ToolActionBar,ToolLayout,decodeBase64,useFocusOnActivate,type PendingAction,type ToolId} from './shared'
import {toast} from './AppToast'
import './JwtTool.css'
type Decoded={header:string;payload:string}
function decodeSegment(segment:string):string|null{const decoded=decodeBase64(segment);if(decoded===null)return null;try{return JSON.stringify(JSON.parse(decoded),null,2)}catch{return null}}
function decodeJwt(token:string):Decoded|null{const parts=token.trim().split('.');if(parts.length!==3)return null;const header=decodeSegment(parts[0]);const payload=decodeSegment(parts[1]);return header!==null&&payload!==null?{header,payload}:null}
export default function JwtTool({active,theme,record,pending,clearPending}:{active:boolean;theme:string;record:(tool:ToolId,action:string,detail:string,input:string,output?:string)=>void;pending:PendingAction|null;clearPending:()=>void}){const{t}=useTranslation();const[input,setInput]=useState('');const[copied,setCopied]=useState<'header'|'payload'|null>(null);const consumed=useRef<PendingAction|null>(null);const copyTimer=useRef<number|null>(null);const inputView=useRef<EditorView|null>(null);useFocusOnActivate(active,()=>inputView.current?.focus());const cmTheme=theme==='light'?tokyoNightDay:tokyoNight;const decoded=useMemo(()=>decodeJwt(input),[input]);const invalid=!!input.trim()&&!decoded;const copy=async(kind:'header'|'payload')=>{if(!decoded)return;const value=decoded[kind];await navigator.clipboard?.writeText(value).catch(()=>{});setCopied(kind);if(copyTimer.current!==null)window.clearTimeout(copyTimer.current);copyTimer.current=window.setTimeout(()=>setCopied(null),1200);const bytes=new TextEncoder().encode(value).length;toast(t('toast.copied',{value:`${bytes} B`}));record('jwt',t(kind==='header'?'jwtTool.copyHeader':'jwtTool.copyPayload'),`${bytes} B`,input,value)};const clear=()=>setInput('');useEffect(()=>()=>{if(copyTimer.current!==null)window.clearTimeout(copyTimer.current)},[]);useEffect(()=>{if(!pending||pending.tool!=='jwt'||consumed.current===pending)return;consumed.current=pending;clearPending();if(pending.action==='clear'){clear();return}if(pending.action==='copyHeader'||pending.action==='copyPayload'){if(!decodeJwt(input)){toast(t('jwtTool.invalid'),{variant:'warning'});return}void copy(pending.action==='copyHeader'?'header':'payload');return}setInput(pending.input)},[pending]);const pane=(label:string,value:string,onChange?:(v:string)=>void,onCreate?:(view:EditorView)=>void,readOnly=false)=><div className="editor jwt-cm-pane"><span>{label}</span><CodeMirror className="jwt-cm" height="100%" value={value} onChange={onChange} readOnly={readOnly} editable={!readOnly} onCreateEditor={onCreate} theme={cmTheme} extensions={readOnly?[json(),EditorView.lineWrapping]:[EditorView.lineWrapping]} basicSetup={{lineNumbers:false,foldGutter:false,highlightActiveLine:false,highlightActiveLineGutter:false,autocompletion:false,closeBrackets:false}}/></div>
return <Reveal index={0} fill active={active}><ToolLayout title={t('jwtTool.title')} desc={t('jwtTool.subtitle')} className="jwt-page" contentMode="fixed" footer={<ToolActionBar label={t('jwtTool.actions')} actions={[{key:'clear',label:t('jwtTool.clear'),icon:Trash,variant:'tertiary',disabled:!input,onPress:clear},{key:'copyHeader',label:copied==='header'?t('jwtTool.copied'):t('jwtTool.copyHeader'),icon:copied==='header'?Check:Copy,variant:'secondary',disabled:!decoded,onPress:()=>copy('header')},{key:'copyPayload',label:copied==='payload'?t('jwtTool.copied'):t('jwtTool.copyPayload'),icon:copied==='payload'?Check:Copy,variant:'primary',disabled:!decoded,onPress:()=>copy('payload')}]}/>}><div className="jwt-layout">{pane(t('jwtTool.input'),input,v=>setInput(v),v=>{inputView.current=v})}<div className="jwt-right">{pane(t('jwtTool.header'),decoded?.header??'',undefined,undefined,true)}{pane(t('jwtTool.payload'),decoded?.payload??'',undefined,undefined,true)}</div></div><div className={`detected${invalid?' invalid':''}`}><span>{t('jwtTool.detected')}</span>{input?<strong>{decoded?t('jwtTool.valid'):t('jwtTool.invalid')}</strong>:<strong className="jwt-detected-empty">{t('jwtTool.emptyHint')}</strong>}</div></ToolLayout></Reveal>}
