import {useEffect, useRef, useState} from 'react'
import {Button, Switch} from '@heroui/react'
import {BracketsCurly} from '@phosphor-icons/react'

export type ToolId = 'json' | 'time' | 'text' | 'base64' | 'diff'
export type PendingAction = {tool:ToolId;action:string;input:string;output?:string;mode?:string}
export type Icon = typeof BracketsCurly
export function stripJsonComments(s:string){let out='',inStr=false,esc=false;for(let i=0;i<s.length;i++){const c=s[i];if(inStr){out+=c;if(esc)esc=false;else if(c==='\\')esc=true;else if(c==='"')inStr=false;continue}if(c==='"'){inStr=true;out+=c;continue}if(c==='/'&&s[i+1]==='/'){while(i<s.length&&s[i]!=='\n')i++;out+='\n';continue}if(c==='/'&&s[i+1]==='*'){i+=2;while(i<s.length&&!(s[i]==='*'&&s[i+1]==='/'))i++;i++;continue}out+=c}return out}
export function stripTrailingCommas(s:string){let out='',inStr=false,esc=false;for(let i=0;i<s.length;i++){const c=s[i];if(inStr){out+=c;if(esc)esc=false;else if(c==='\\')esc=true;else if(c==='"')inStr=false;continue}if(c==='"'){inStr=true;out+=c;continue}if(c===','){let j=i+1;while(j<s.length&&/\s/.test(s[j]))j++;if(s[j]==='}'||s[j]===']')continue}out+=c}return out}
export function parseJsonLoose(s:string){return JSON.parse(stripTrailingCommas(stripJsonComments(s)))}
export function hasComments(s:string){return stripJsonComments(s)!==s}
export function formatJsonPreserve(src:string){const toks:Array<{t:string;v:string;ls:boolean}>=[];let i=0,ls=true;while(i<src.length){const c=src[i];if(c==='"'||c==="'"){const q=c;let v=q;i++;while(i<src.length){const ch=src[i];v+=ch;i++;if(ch==='\\'){if(i<src.length){v+=src[i];i++}continue}if(ch===q)break}toks.push({t:'str',v,ls});ls=false}else if(c==='/'&&src[i+1]==='/'){let v='';while(i<src.length&&src[i]!=='\n'){v+=src[i];i++}toks.push({t:'line',v,ls});ls=false}else if(c==='/'&&src[i+1]==='*'){let v='/*';i+=2;while(i<src.length&&!(src[i]==='*'&&src[i+1]==='/')){v+=src[i];i++}if(src[i]){v+='*/';i+=2}toks.push({t:'block',v,ls});ls=false}else if('{}[],:'.includes(c)){toks.push({t:c,v:c,ls});ls=false;i++}else if(/\s/.test(c)){if(c==='\n')ls=true;i++}else{let v='';while(i<src.length&&!/[\s{}[\]:,'"\/]/.test(src[i])){v+=src[i];i++}toks.push({t:'v',v,ls});ls=false}}let out='',depth=0,lsOut=true,inValue=false;const ind=()=>'  '.repeat(depth);const nl=()=>{out+='\n'+ind();lsOut=true};for(let k=0;k<toks.length;k++){const x=toks[k];if(x.t==='{'||x.t==='['){const close=x.t==='{'?'}':']';if(k+1<toks.length&&toks[k+1].t===close){if(!lsOut&&!inValue)nl();out+=x.t+close;lsOut=false;inValue=false;k++;continue}if(!inValue&&!lsOut)nl();out+=x.t;depth++;nl();lsOut=true;inValue=false}else if(x.t==='}'||x.t===']'){depth=Math.max(0,depth-1);out=out.replace(/\s+$/,'');nl();out+=x.t;lsOut=false;inValue=false}else if(x.t===':'){out+=': ';lsOut=false;inValue=true}else if(x.t===','){out+=',';nl();inValue=false}else if(x.t==='line'){if(x.ls){if(!lsOut)nl();out+=x.v;nl()}else{if(!lsOut)out+=' ';out+=x.v;nl()}}else if(x.t==='block'){if(x.ls){if(!lsOut)nl();out+=x.v;lsOut=false}else{if(!lsOut)out+=' ';out+=x.v;lsOut=false}}else{if(!inValue&&!lsOut)nl();out+=x.v;lsOut=false;inValue=false}}return out}
export const samples={json:'{"project":"DevUtils","version":1,"features":["search","clipboard","privacy"],"owner":{"team":"developer experience","active":true}}',text:'  Build tools that stay out of the way.\nShip faster, keep data local.  '}
export function Reveal({children,index,fill,active}:{children:React.ReactNode;index?:number;fill?:boolean;active?:boolean}){const ref=useRef<HTMLDivElement>(null);const[visible,setVisible]=useState(false);useEffect(()=>{if(active!==undefined){setVisible(active);return}const el=ref.current;if(!el)return;const io=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);io.disconnect()}},{threshold:.12});io.observe(el);return()=>io.disconnect()},[active]);return<div ref={ref} className={`reveal${visible?' is-visible':''}${fill?' reveal-fill':''}`} style={{'--index':index??0} as React.CSSProperties}>{children}</div>}
export type ToolAction={key:string;label:string;icon?:Icon;active?:boolean;type?:'toggle';checked?:boolean;onPress:()=>void}
export function ToolHeader({title,desc,actions=[]}:{title:string;desc?:string;actions?:ToolAction[]}){return <header className="tool-header"><div className="tool-heading"><h1>{title}</h1>{desc?<p>{desc}</p>:null}</div>{actions.length>0&&<div className="tool-header-actions">{actions.map(a=>a.type==='toggle'?<label key={a.key} className="tool-header-action tool-header-toggle"><span>{a.label}</span><Switch isSelected={!!a.checked} onChange={a.onPress}><Switch.Content><Switch.Control><Switch.Thumb/></Switch.Control></Switch.Content></Switch></label>:<button key={a.key} className={`tool-header-action${a.active?' active':''}`} aria-pressed={a.active} onClick={a.onPress}>{a.icon&&<a.icon size={14} weight="duotone"/>}{a.label}</button>)}</div>}</header>}
export function ToolLayout({title,desc,actions,footer,children,className='',contentMode='scroll'}:{title:string;desc?:string;actions?:ToolAction[];footer?:React.ReactNode;children:React.ReactNode;className?:string;contentMode?:'scroll'|'fixed'}){return <section className={`tool-page tool-layout${className?` ${className}`:''}`}><ToolHeader title={title} desc={desc} actions={actions}/><div className={`tool-layout-content is-${contentMode}`}>{children}</div><footer className="tool-layout-footer">{footer}</footer></section>}
export type ToolBarAction={key:string;label:string;icon?:Icon;variant:'primary'|'secondary'|'tertiary'|'danger';disabled?:boolean;onPress:()=>void}
export function ToolActionBar({label,actions}:{label:string;actions:ToolBarAction[]}){return <div className="tool-action-bar" role="toolbar" aria-label={label}>{actions.map(action=><Button key={action.key} variant={action.variant} isDisabled={action.disabled} onPress={action.onPress}>{action.icon&&<action.icon size={14} weight="duotone"/>}{action.label}</Button>)}</div>}
export function Editor({label,value,onChange,readOnly,onKeyDown}:{label:string;value:string;onChange?:(v:string)=>void;readOnly?:boolean;onKeyDown?:(e:React.KeyboardEvent<HTMLTextAreaElement>)=>void}){return <label className="editor"><span>{label}</span><textarea value={value} readOnly={readOnly} spellCheck={false} onChange={e=>onChange?.(e.target.value)} onKeyDown={onKeyDown}/></label>}
export function useHistory(initial:string){const[value,setValueState]=useState(initial);const valueRef=useRef(initial);const past=useRef<string[]>([]);const future=useRef<string[]>([]);const lastAt=useRef(0);const commit=(next:string,opts?:{isolate?:boolean})=>{const cur=valueRef.current;if(next===cur)return;const now=Date.now();if(!opts?.isolate&&now-lastAt.current<600&&past.current.length)past.current[past.current.length-1]=cur;else{past.current.push(cur);if(past.current.length>100)past.current.shift()}future.current=[];lastAt.current=now;valueRef.current=next;setValueState(next)};const undo=()=>{if(!past.current.length)return;future.current.push(valueRef.current);valueRef.current=past.current.pop()!;setValueState(valueRef.current);lastAt.current=0};const redo=()=>{if(!future.current.length)return;past.current.push(valueRef.current);valueRef.current=future.current.pop()!;setValueState(valueRef.current);lastAt.current=0};return{value,setValue:commit,undo,redo}}
export function undoRedoKey(e:React.KeyboardEvent,undo:()=>void,redo:()=>void){if(e.nativeEvent.isComposing)return false;const mod=e.metaKey||e.ctrlKey;const key=e.key.toLowerCase();if(mod&&key==='z'&&!e.shiftKey){e.preventDefault();undo();return true}if((mod&&key==='z'&&e.shiftKey)||(mod&&key==='y')){e.preventDefault();redo();return true}return false}
