import {useEffect, useRef, useState} from 'react'
import {BracketsCurly} from '@phosphor-icons/react'

export type ToolId = 'json' | 'time' | 'text'
export type PendingAction = {tool:ToolId;action:string;input:string}
export type Icon = typeof BracketsCurly
export const samples={json:'{"project":"DevUtils","version":1,"features":["search","clipboard","privacy"],"owner":{"team":"developer experience","active":true}}',text:'  Build tools that stay out of the way.\nShip faster, keep data local.  '}
export function Reveal({children,index,fill,active}:{children:React.ReactNode;index?:number;fill?:boolean;active?:boolean}){const ref=useRef<HTMLDivElement>(null);const[visible,setVisible]=useState(false);useEffect(()=>{if(active!==undefined){setVisible(active);return}const el=ref.current;if(!el)return;const io=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);io.disconnect()}},{threshold:.12});io.observe(el);return()=>io.disconnect()},[active]);return<div ref={ref} className={`reveal${visible?' is-visible':''}${fill?' reveal-fill':''}`} style={{'--index':index??0} as React.CSSProperties}>{children}</div>}
export function ToolHeader({icon:Icon,title,subtitle}:{icon:Icon;title:string;subtitle:string}){return <header className="tool-header"><span className="tool-heading-icon"><Icon size={17} weight="bold"/></span><div><h1>{title}</h1><p>{subtitle}</p></div></header>}
export function Editor({label,value,onChange,readOnly,onKeyDown}:{label:string;value:string;onChange?:(v:string)=>void;readOnly?:boolean;onKeyDown?:(e:React.KeyboardEvent<HTMLTextAreaElement>)=>void}){return <label className="editor"><span>{label}</span><textarea value={value} readOnly={readOnly} spellCheck={false} onChange={e=>onChange?.(e.target.value)} onKeyDown={onKeyDown}/></label>}
export function useHistory(initial:string){const[value,setValueState]=useState(initial);const valueRef=useRef(initial);const past=useRef<string[]>([]);const future=useRef<string[]>([]);const lastAt=useRef(0);const commit=(next:string,opts?:{isolate?:boolean})=>{const cur=valueRef.current;if(next===cur)return;const now=Date.now();if(!opts?.isolate&&now-lastAt.current<600&&past.current.length)past.current[past.current.length-1]=cur;else{past.current.push(cur);if(past.current.length>100)past.current.shift()}future.current=[];lastAt.current=now;valueRef.current=next;setValueState(next)};const undo=()=>{if(!past.current.length)return;future.current.push(valueRef.current);valueRef.current=past.current.pop()!;setValueState(valueRef.current);lastAt.current=0};const redo=()=>{if(!future.current.length)return;past.current.push(valueRef.current);valueRef.current=future.current.pop()!;setValueState(valueRef.current);lastAt.current=0};return{value,setValue:commit,undo,redo}}
export function undoRedoKey(e:React.KeyboardEvent,undo:()=>void,redo:()=>void){if(e.nativeEvent.isComposing)return false;const mod=e.metaKey||e.ctrlKey;const key=e.key.toLowerCase();if(mod&&key==='z'&&!e.shiftKey){e.preventDefault();undo();return true}if((mod&&key==='z'&&e.shiftKey)||(mod&&key==='y')){e.preventDefault();redo();return true}return false}
