import {useEffect, useMemo, useRef} from 'react'
import {Button} from '@heroui/react'
import {useTranslation} from 'react-i18next'
import {TextT, Trash} from '@phosphor-icons/react'
import {Editor, Reveal, ToolHeader, samples, undoRedoKey, useHistory, type PendingAction, type ToolId} from './shared'

export default function TextTool({active,record,pending,clearPending}:{active:boolean;record:(tool:ToolId,action:string,detail:string)=>void;pending:PendingAction|null;clearPending:()=>void}){
  const{t}=useTranslation();const{value,setValue,undo,redo}=useHistory(samples.text);const consumed=useRef<PendingAction|null>(null);const stats=useMemo(()=>({characters:[...value].length,words:value.trim()?value.trim().split(/\s+/).length:0,lines:value?value.split(/\r?\n/).length:0,bytes:new TextEncoder().encode(value).length}),[value]);const apply=(action:string,transform:(v:string)=>string)=>{setValue(transform(value),{isolate:true});record('text',action,`${stats.characters} ${t('textTool.characters')}`)}
  useEffect(()=>{if(!pending||pending.tool!=='text'||consumed.current===pending)return;consumed.current=pending;clearPending();setValue(pending.input,{isolate:true});const labels:Record<string,string>={trim:t('textTool.trimmed'),removeSpaces:t('textTool.removedSpaces'),compress:t('textTool.compressed'),count:t('textTool.count')};const transforms:Record<string,(s:string)=>string>={trim:s=>s.trim(),removeSpaces:s=>s.replace(/[ \t]+/g,''),compress:s=>s.replace(/\s+/g,' ').trim(),count:s=>s};const transform=transforms[pending.action];if(transform){const next=transform(pending.input);if(next!==pending.input)setValue(next,{isolate:true});record('text',labels[pending.action]??pending.action,`${[...next].length} ${t('textTool.characters')}`)}},[pending])
  return <Reveal index={0} active={active}><section className="tool-page"><ToolHeader icon={TextT} title={t('textTool.title')} subtitle={t('textTool.subtitle')}/><Editor label={t('textTool.input')} value={value} onChange={setValue} onKeyDown={e=>undoRedoKey(e,undo,redo)}/><div className="stat-grid">{Object.entries(stats).map(([label,number])=><div key={label}><span>{t(`textTool.${label}`)}</span><strong>{number.toLocaleString()}</strong></div>)}</div><div className="tool-actions wrap"><Button variant="primary" onPress={()=>apply(t('textTool.trimmed'),v=>v.trim())}>{t('textTool.trim')}</Button><Button variant="secondary" onPress={()=>apply(t('textTool.removedSpaces'),v=>v.replace(/[ \t]+/g,''))}>{t('textTool.removeSpaces')}</Button><Button variant="secondary" onPress={()=>apply(t('textTool.compressed'),v=>v.replace(/\s+/g,' ').trim())}>{t('textTool.compressWhitespace')}</Button><Button variant="tertiary" onPress={()=>{setValue('',{isolate:true});record('text',t('textTool.cleared'),t('textTool.cleared'))}}><Trash weight="bold"/>{t('textTool.clear')}</Button></div></section></Reveal>
}
