import {useEffect, useMemo, useRef} from 'react'
import {Button, Popover} from '@heroui/react'
import {useTranslation} from 'react-i18next'
import {Trash} from '@phosphor-icons/react'
import {Editor, Reveal, ToolHeader, samples, undoRedoKey, useHistory, type PendingAction, type ToolId} from './shared'

const countDetails=(characters:string[])=>Array.from(characters.reduce((counts,character)=>counts.set(character,(counts.get(character)??0)+1),new Map<string,number>())).sort(([left],[right])=>left.localeCompare(right,'zh-CN'))
const words=(value:string)=>value.match(/[\p{L}\p{N}]+(?:['’-][\p{L}\p{N}]+)*/gu)??[]

export default function TextTool({active,record,pending,clearPending}:{active:boolean;record:(tool:ToolId,action:string,detail:string,input:string)=>void;pending:PendingAction|null;clearPending:()=>void}){
  const{t}=useTranslation();const{value,setValue,undo,redo}=useHistory(samples.text);const consumed=useRef<PendingAction|null>(null);const stats=useMemo(()=>{const characters=[...value];const wordList=words(value);const details:Array<[string,string[]]>=[['chinese',characters.filter(character=>/[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]/u.test(character))],['english',characters.filter(character=>/[A-Za-z]/.test(character))],['digits',characters.filter(character=>/\d/.test(character))],['words',wordList],['punctuation',characters.filter(character=>/[\p{P}]/u.test(character))]];return[...details.map(([key,items])=>({key,count:items.length,details:countDetails(items),detail:true})),{key:'lines',count:value?value.split(/\r?\n/).length:0,details:[],detail:false},{key:'bytes',count:new TextEncoder().encode(value).length,details:[],detail:false}]},[value]);const apply=(action:string,transform:(v:string)=>string)=>{const next=transform(value);setValue(next,{isolate:true});record('text',action,`${[...next].length} ${t('textTool.characters')}`,next)}
  useEffect(()=>{if(!pending||pending.tool!=='text'||consumed.current===pending)return;consumed.current=pending;clearPending();setValue(pending.input,{isolate:true});if(pending.action==='restore')return;const labels:Record<string,string>={trim:t('textTool.trimmed'),removeSpaces:t('textTool.removedSpaces'),compress:t('textTool.compressed'),count:t('textTool.count')};const transforms:Record<string,(s:string)=>string>={trim:s=>s.trim(),removeSpaces:s=>s.replace(/[ \t]+/g,''),compress:s=>s.replace(/\s+/g,' ').trim(),count:s=>s};const transform=transforms[pending.action];if(transform){const next=transform(pending.input);if(next!==pending.input)setValue(next,{isolate:true});record('text',labels[pending.action]??pending.action,`${[...next].length} ${t('textTool.characters')}`,next)}},[pending])
  return <Reveal index={0} active={active}><section className="tool-page"><ToolHeader title={t('textTool.title')} desc={t('textTool.subtitle')}/><Editor label={t('textTool.input')} value={value} onChange={setValue} onKeyDown={e=>undoRedoKey(e,undo,redo)}/><div className="stat-grid text-stat-grid">{stats.map(stat=><div key={stat.key}>{stat.detail?<Popover><Popover.Trigger><button className="stat-detail-trigger" aria-label={t('textTool.showDetails',{label:t(`textTool.${stat.key}`)})}><span>{t(`textTool.${stat.key}`)}</span><strong>{stat.count.toLocaleString()}</strong></button></Popover.Trigger><Popover.Content className="text-stat-popover" offset={8}><Popover.Dialog><Popover.Heading>{t('textTool.detailTitle',{label:t(`textTool.${stat.key}`)})}</Popover.Heading><div className="text-stat-details">{stat.details.length?stat.details.map(([character,count])=><div key={character}><code>{character}</code><span>{count.toLocaleString()}</span></div>):<p>{t('textTool.noDetails')}</p>}</div></Popover.Dialog></Popover.Content></Popover>:<><span>{t(`textTool.${stat.key}`)}</span><strong>{stat.count.toLocaleString()}</strong></>}</div>)}</div><div className="tool-actions wrap"><Button variant="primary" onPress={()=>apply(t('textTool.trimmed'),v=>v.trim())}>{t('textTool.trim')}</Button><Button variant="secondary" onPress={()=>apply(t('textTool.compressed'),v=>v.replace(/\s+/g,' ').trim())}>{t('textTool.compressWhitespace')}</Button><Button variant="secondary" onPress={()=>apply(t('textTool.removedSpaces'),v=>v.replace(/[ \t]+/g,''))}>{t('textTool.removeSpaces')}</Button><Button variant="tertiary" onPress={()=>{setValue('',{isolate:true});record('text',t('textTool.cleared'),t('textTool.cleared'),'')}}><Trash weight="duotone"/>{t('textTool.clear')}</Button></div></section></Reveal>
}
