import {useEffect, useMemo, useRef, useState} from 'react'
import {Button, Popover, Table, type SortDescriptor} from '@heroui/react'
import {useTranslation} from 'react-i18next'
import {Trash} from '@phosphor-icons/react'
import {Editor, Reveal, ToolHeader, samples, undoRedoKey, useHistory, type PendingAction, type ToolId} from './shared'
import {toast} from './AppToast'

const countDetails=(characters:string[])=>Array.from(characters.reduce((counts,character)=>counts.set(character,(counts.get(character)??0)+1),new Map<string,number>())).sort(([left],[right])=>left.localeCompare(right,'zh-CN'))
const words=(value:string)=>value.match(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g)??[]

export default function TextTool({active,record,pending,clearPending}:{active:boolean;record:(tool:ToolId,action:string,detail:string,input:string)=>void;pending:PendingAction|null;clearPending:()=>void}){
  const{t}=useTranslation();const{value,setValue,undo,redo}=useHistory(samples.text);const consumed=useRef<PendingAction|null>(null);const[sortDescriptor,setSortDescriptor]=useState<SortDescriptor>({column:'count',direction:'descending'});const stats=useMemo(()=>{const characters=[...value];const wordList=words(value);const details:Array<[string,string[]]>=[['chinese',characters.filter(character=>/[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]/u.test(character))],['english',characters.filter(character=>/[A-Za-z]/.test(character))],['digits',characters.filter(character=>/\d/.test(character))],['words',wordList],['punctuation',characters.filter(character=>/[\p{P}]/u.test(character))]];return[...details.map(([key,items])=>({key,count:items.length,details:countDetails(items),detail:items.length>0})),{key:'lines',count:value?value.split(/\r?\n/).length:0,details:[],detail:false},{key:'bytes',count:new TextEncoder().encode(value).length,details:[],detail:false}]},[value]);const sortDetails=(details:Array<[string,number]>)=>[...details].sort(([leftName,leftCount],[rightName,rightCount])=>{const order=sortDescriptor.column==='count'?leftCount-rightCount:leftName.localeCompare(rightName,'zh-CN');return sortDescriptor.direction==='descending'?-order:order});const copyDetail=(character:string,count:number)=>{const copied=`${character}: ${count}`;navigator.clipboard?.writeText(copied);toast(t('toast.copied',{value:copied}));record('text',t('textTool.copied'),copied,value)};const apply=(action:string,transform:(v:string)=>string)=>{const next=transform(value);setValue(next,{isolate:true});record('text',action,`${[...next].length} ${t('textTool.characters')}`,next)}
  useEffect(()=>{if(!pending||pending.tool!=='text'||consumed.current===pending)return;consumed.current=pending;clearPending();setValue(pending.input,{isolate:true});if(pending.action==='restore')return;const labels:Record<string,string>={trim:t('textTool.trimmed'),removeSpaces:t('textTool.removedSpaces'),compress:t('textTool.compressedSpaces'),compressLine:t('textTool.compressedLine'),count:t('textTool.count')};const transforms:Record<string,(s:string)=>string>={trim:s=>s.trim(),removeSpaces:s=>s.replace(/[ \t]+/g,''),compress:s=>s.replace(/ {2,}/g,' '),compressLine:s=>s.replace(/\r\n?|\n/g,' '),count:s=>s};const transform=transforms[pending.action];if(transform){const next=transform(pending.input);if(next!==pending.input)setValue(next,{isolate:true});record('text',labels[pending.action]??pending.action,`${[...next].length} ${t('textTool.characters')}`,next)}},[pending])
  return <Reveal index={0} active={active}><section className="tool-page"><ToolHeader title={t('textTool.title')} desc={t('textTool.subtitle')}/><Editor label={t('textTool.input')} value={value} onChange={setValue} onKeyDown={e=>undoRedoKey(e,undo,redo)}/><div className="stat-grid text-stat-grid">{stats.map(stat=><div key={stat.key}>{stat.detail?<Popover><Popover.Trigger><button className="stat-detail-trigger" aria-label={t('textTool.showDetails',{label:t(`textTool.${stat.key}`)})}><span>{t(`textTool.${stat.key}`)}</span><strong>{stat.count.toLocaleString()}</strong></button></Popover.Trigger><Popover.Content className="text-stat-dialog-popover"><Popover.Dialog className="text-stat-dialog">{stat.details.length?<Table className="text-stat-table"><Table.ScrollContainer className="scrollbar-thin text-stat-table-scroll"><Table.Content className="text-stat-table-sticky" aria-label={t('textTool.detailTitle',{label:t(`textTool.${stat.key}`)})} sortDescriptor={sortDescriptor} onSortChange={setSortDescriptor}><Table.Header><Table.Column id="entry" isRowHeader allowsSorting>{({sortDirection})=><Table.SortableColumnHeader sortDirection={sortDirection}>{t('textTool.detailEntry')}</Table.SortableColumnHeader>}</Table.Column><Table.Column id="count" allowsSorting>{({sortDirection})=><Table.SortableColumnHeader sortDirection={sortDirection}>{t('textTool.detailCount')}</Table.SortableColumnHeader>}</Table.Column></Table.Header><Table.Body>{sortDetails(stat.details).map(([character,count])=><Table.Row key={character} id={character} textValue={`${character}: ${count}`} onAction={()=>copyDetail(character,count)}><Table.Cell>{character}</Table.Cell><Table.Cell>{count.toLocaleString()}</Table.Cell></Table.Row>)}</Table.Body></Table.Content></Table.ScrollContainer></Table>:<p>{t('textTool.noDetails')}</p>}</Popover.Dialog></Popover.Content></Popover>:<><span>{t(`textTool.${stat.key}`)}</span><strong>{stat.count.toLocaleString()}</strong></>}</div>)}</div><div className="tool-actions wrap"><Button variant="secondary" onPress={()=>apply(t('textTool.trimmed'),v=>v.trim())}>{t('textTool.trim')}</Button><Button variant="secondary" onPress={()=>apply(t('textTool.compressedSpaces'),v=>v.replace(/ {2,}/g,' '))}>{t('textTool.compressSpaces')}</Button><Button variant="secondary" onPress={()=>apply(t('textTool.removedSpaces'),v=>v.replace(/[ \t]+/g,''))}>{t('textTool.removeSpaces')}</Button><Button variant="secondary" onPress={()=>apply(t('textTool.compressedLine'),v=>v.replace(/\r\n?|\n/g,' '))}>{t('textTool.compressLine')}</Button><Button variant="tertiary" onPress={()=>{setValue('',{isolate:true});record('text',t('textTool.cleared'),t('textTool.cleared'),'')}}><Trash weight="duotone"/>{t('textTool.clear')}</Button></div></section></Reveal>
}
