import {useEffect, useMemo, useRef} from 'react'
import {useTranslation} from 'react-i18next'
import {Clock, Copy} from '@phosphor-icons/react'
import {Reveal, ToolHeader, undoRedoKey, useHistory, type PendingAction, type ToolId} from './shared'

export default function TimeTool({active,record,pending,clearPending}:{active:boolean;record:(tool:ToolId,action:string,detail:string)=>void;pending:PendingAction|null;clearPending:()=>void}){
  const{t}=useTranslation();const{value:input,setValue:setInput,undo,redo}=useHistory('1786358400');const consumed=useRef<PendingAction|null>(null);const parsed=useMemo(()=>{const raw=input.trim();if(!raw)return null;const numeric=Number(raw);const date=/^\d{10,13}$/.test(raw)?new Date(raw.length===10?numeric*1000:numeric):new Date(raw);return Number.isNaN(date.getTime())?null:date},[input]);const values=parsed?[[t('timeTool.localTime'),parsed.toLocaleString()],[t('timeTool.utc'),parsed.toUTCString()],[t('timeTool.rfc3339'),parsed.toISOString()],[t('timeTool.unixSeconds'),Math.floor(parsed.getTime()/1000).toString()]]:[]
  useEffect(()=>{if(!pending||pending.tool!=='time'||consumed.current===pending)return;consumed.current=pending;clearPending();setInput(pending.input,{isolate:true});record('time',t('timeTool.converted'),pending.input.trim().slice(0,40))},[pending])
  return <Reveal index={0} active={active}><section className="tool-page"><ToolHeader icon={Clock} title={t('timeTool.title')} subtitle={t('timeTool.subtitle')}/><label className="field"><span>{t('timeTool.input')}</span><div className="field-control"><Clock size={18} weight="duotone"/><input value={input} onKeyDown={e=>undoRedoKey(e,undo,redo)} onChange={e=>setInput(e.target.value)} placeholder={t('timeTool.placeholder')}/></div><small>{t('timeTool.hint')}</small></label><div className={`detected ${parsed?'':'invalid'}`}><span>{t('timeTool.detected')}</span><strong>{parsed?(/^\d{10}$/.test(input.trim())?t('timeTool.unixSec'):/^\d{13}$/.test(input.trim())?t('timeTool.unixMs'):t('timeTool.dateString')):t('timeTool.unrecognized')}</strong></div>{parsed?<div className="conversion-list">{values.map(([label,value])=><div key={label}><span>{label}</span><code>{value}</code><button aria-label={t('timeTool.copy',{label})} onClick={()=>{navigator.clipboard?.writeText(value);record('time',t('timeTool.converted'),label)}}><Copy size={15} weight="duotone"/></button></div>)}</div>:<div className="empty-state compact"><Clock size={24} weight="duotone"/><strong>{t('timeTool.emptyTitle')}</strong><span>{t('timeTool.emptyHint')}</span></div>}</section></Reveal>
}
