// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "trayMatchEnabled": boolean;
    "trayMatchTools": string[] | null;
    "urlTrayMatchMigrated": boolean;
    "autoOverwrite": boolean;
    "autoCheckUpdates": boolean;
    "language": string;
    "sidebarMode": string;
    "sidebarTools": SidebarToolConfig[] | null;
    "themeMode": string;
    "lightTheme": string;
    "darkTheme": string;
    "diffClipboardTargetMode": string;
    "codeEditorFontSize": number;
    "timeResultOrder": string[] | null;
    "hiddenTimeResults": string[] | null;
    "jsonAutoFormatOnFill": boolean;
    "jsonAutoFormatOnFillMigrated": boolean;
    "dockerCLIPath": string;
    "imageSources": ImageSource[] | null;
}

export interface DockerDeleteFailure {
    "imageID": string;
    "error": string;
}

export interface DockerDeleteResult {
    "deleted": string[] | null;
    "failed": DockerDeleteFailure[] | null;
}

export interface DockerHealthcheck {
    "test": string[] | null;
    "interval": string;
    "timeout": string;
    "startPeriod": string;
    "retries": number;
}

export interface DockerImage {
    "id": string;
    "name": string;
    "tags": string[] | null;
    "repository": string;
    "digest": string;
    "mediaType": string;
    "sizeType": string;
    "size": string;
    "sizeBytes": number;
    "createdAt": string;
}

export interface DockerImageDetail {
    "id": string;
    "name": string;
    "tags": string[] | null;
    "size": number;
    "createdAt": string;
    "architecture": string;
    "os": string;
    "labels": { [_ in string]?: string } | null;
    "command": string[] | null;
    "entrypoint": string[] | null;
    "repository": string;
    "digest": string;
    "mediaType": string;
    "sizeType": string;
    "manifest": RegistryManifest | null;
    "index": RegistryIndex | null;
    "metadata": DockerImageMetadata;
    "layers": DockerImageLayer[] | null;
    "runtime": DockerRuntimeConfig;
    "rawManifest": string;
}

export interface DockerImageLayer {
    "size": number;
    "digest": string;
    "mediaType": string;
}

export interface DockerImageMetadata {
    "createdAt": string;
    "architecture": string;
    "os": string;
    "osVersion": string;
    "variant": string;
    "author": string;
    "dockerVersion": string;
    "container": string;
    "configDigest": string;
    "rootfsType": string;
    "diffIDs": string[] | null;
}

export interface DockerOperationResult {
    "success": boolean;
    "image": string;
    "output": string;
    "error": string;
}

export interface DockerRuntimeConfig {
    "user": string;
    "workingDir": string;
    "env": string[] | null;
    "exposedPorts": string[] | null;
    "volumes": string[] | null;
    "stopSignal": string;
    "shell": string[] | null;
    "command": string[] | null;
    "entrypoint": string[] | null;
    "healthcheck": DockerHealthcheck | null;
    "tty": boolean;
    "openStdin": boolean;
    "networkDisabled": boolean;
}

export interface DockerStatus {
    "available": boolean;
    "cliPath": string;
    "version": string;
    "error": string;
}

export interface HistoryContent {
    "input": string;
    "output": string;
}

export interface HistoryEntry {
    "tool": string;
    "action": string;
    "detail": string;
    "mode": string;
    "mediaType": string;
    "name": string;
    "bytes": number;
    "input": string;
    "output": string;
}

export interface HistoryFilter {
    "tool": string;
    "from": number;
    "to": number;
}

export interface HistoryItem {
    "id": number;
    "tool": string;
    "action": string;
    "detail": string;
    "at": string;
    "mode": string;
    "mediaType": string;
    "name": string;
    "bytes": number;
}

export interface HistoryPage {
    "items": HistoryItem[] | null;
    "total": number;
}

export interface ImageExportResult {
    "started": number;
    "snapshot": ImageTaskSnapshot;
}

export interface ImageSource {
    "id": string;
    "name": string;
    "kind": string;
    "sshHost": string;
    "sshPort": number;
    "sshUsername": string;
    "sshPassword": string;
    "sshPrivateKey": string;
    "sshPrivateKeyPath": string;
    "sshKeyPassphrase": string;
    "registryURL": string;
    "registryUsername": string;
    "registryPassword": string;
}

export interface ImageTask {
    "id": string;
    "type": string;
    "sourceID": string;
    "imageID": string;
    "status": string;
    "stage": string;
    "completed": number;
    "total": number;
    "bytes": number;
    "error"?: string;
    "path"?: string;
    "createdAt": string;
    "updatedAt": string;
}

export interface ImageTaskSnapshot {
    "revision": number;
    "tasks": ImageTask[] | null;
}

export interface RegistryDescriptor {
    "mediaType": string;
    "digest": string;
    "size": number;
    "platform": RegistryPlatform | null;
}

export interface RegistryIndex {
    "schemaVersion": number;
    "mediaType": string;
    "manifests": RegistryDescriptor[] | null;
}

export interface RegistryManifest {
    "schemaVersion": number;
    "mediaType": string;
    "config": RegistryDescriptor;
    "layers": RegistryDescriptor[] | null;
}

export interface RegistryPlatform {
    "architecture": string;
    "os": string;
    "variant": string;
}

/**
 * SSHConfigHost 是 ~/.ssh/config 中可以直接交给系统 ssh 的 Host 别名。
 */
export interface SSHConfigHost {
    "alias": string;
}

export interface SidebarToolConfig {
    "id": string;
    "enabled": boolean;
}

/**
 * SystemInfo 描述运行 DevUtils 的操作系统环境。
 */
export interface SystemInfo {
    "os": string;
    "version": string;
    "arch": string;
}
