// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "trayMatchEnabled": boolean;
    "trayMatchTools": string[] | null;
    "urlTrayMatchMigrated": boolean;
    "autoOverwrite": boolean;
    "autoCheckUpdates": boolean;
    "language": string;
    "sidebarMode": string;
    "sidebarTools": SidebarToolConfig[] | null;
    "themeMode": string;
    "lightTheme": string;
    "darkTheme": string;
    "diffClipboardTargetMode": string;
    "codeEditorFontSize": number;
    "timeResultOrder": string[] | null;
    "hiddenTimeResults": string[] | null;
    "jsonAutoFormatOnFill": boolean;
    "jsonAutoFormatOnFillMigrated": boolean;
    "dockerCLIPath": string;
    "imageSources": ImageSource[] | null;
}

export interface DockerDeleteFailure {
    "imageID": string;
    "error": string;
}

export interface DockerDeleteResult {
    "deleted": string[] | null;
    "failed": DockerDeleteFailure[] | null;
}

export interface DockerImage {
    "id": string;
    "name": string;
    "size": string;
    "sizeBytes": number;
    "createdAt": string;
}

export interface DockerImageDetail {
    "id": string;
    "name": string;
    "tags": string[] | null;
    "size": number;
    "createdAt": string;
    "architecture": string;
    "os": string;
    "labels": { [_ in string]?: string } | null;
    "command": string[] | null;
    "entrypoint": string[] | null;
}

export interface DockerOperationResult {
    "success": boolean;
    "image": string;
    "output": string;
    "error": string;
}

export interface DockerStatus {
    "available": boolean;
    "cliPath": string;
    "version": string;
    "error": string;
}

export interface HistoryContent {
    "input": string;
    "output": string;
}

export interface HistoryEntry {
    "tool": string;
    "action": string;
    "detail": string;
    "mode": string;
    "mediaType": string;
    "name": string;
    "bytes": number;
    "input": string;
    "output": string;
}

export interface HistoryFilter {
    "tool": string;
    "from": number;
    "to": number;
}

export interface HistoryItem {
    "id": number;
    "tool": string;
    "action": string;
    "detail": string;
    "at": string;
    "mode": string;
    "mediaType": string;
    "name": string;
    "bytes": number;
}

export interface HistoryPage {
    "items": HistoryItem[] | null;
    "total": number;
}

export interface ImageSource {
    "id": string;
    "name": string;
    "kind": string;
    "sshHost": string;
}

/**
 * SSHConfigHost 是 ~/.ssh/config 中可以直接交给系统 ssh 的 Host 别名。
 */
export interface SSHConfigHost {
    "alias": string;
}

export interface SidebarToolConfig {
    "id": string;
    "enabled": boolean;
}

/**
 * SystemInfo 描述运行 DevUtils 的操作系统环境。
 */
export interface SystemInfo {
    "os": string;
    "version": string;
    "arch": string;
}
