// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "trayMatchEnabled": boolean;
    "trayMatchTools": string[] | null;
    "urlTrayMatchMigrated": boolean;
    "autoOverwrite": boolean;
    "autoCheckUpdates": boolean;
    "language": string;
    "sidebarMode": string;
    "themeMode": string;
    "lightTheme": string;
    "darkTheme": string;
    "diffHighlightMode": string;
    "diffClipboardTargetMode": string;
    "codeEditorFontSize": number;
    "timeResultOrder": string[] | null;
    "hiddenTimeResults": string[] | null;
    "jsonAutoFormatOnFill": boolean;
    "jsonAutoFormatOnFillMigrated": boolean;
}

export interface HistoryContent {
    "input": string;
    "output": string;
}

export interface HistoryEntry {
    "tool": string;
    "action": string;
    "detail": string;
    "mode": string;
    "mediaType": string;
    "name": string;
    "bytes": number;
    "input": string;
    "output": string;
}

export interface HistoryFilter {
    "tool": string;
    "from": number;
    "to": number;
}

export interface HistoryItem {
    "id": number;
    "tool": string;
    "action": string;
    "detail": string;
    "at": string;
    "mode": string;
    "mediaType": string;
    "name": string;
    "bytes": number;
}

export interface HistoryPage {
    "items": HistoryItem[] | null;
    "total": number;
}
