import {useEffect, useMemo, useRef, useState} from 'react'
import {Button, Switch, ToastProvider, toast} from '@heroui/react'
import {Clipboard, Events} from '@wailsio/runtime'
import {useTranslation} from 'react-i18next'
import {pinyin} from 'pinyin-pro'
import {BracketsCurly, CaretRight, Clock, ClockCounterClockwise, GearSix, Hash, Heart, House, MagnifyingGlass, TextT, Trash} from '@phosphor-icons/react'
import i18n, {SUPPORTED_LANGUAGES} from './i18n'
import JsonTool from './components/JsonTool'
import TimeTool from './components/TimeTool'
import TextTool from './components/TextTool'
import {parseJsonLoose, Reveal, type Icon, type PendingAction, type ToolId} from './components/shared'

type Page = 'home' | 'settings' | 'history' | ToolId
type HistoryItem = {id:number;tool:ToolId;action:string;detail:string;at:string}
type Settings = {clipboardDetection:boolean;analyzeOnOpen:boolean;detectJson:boolean;detectTimestamp:boolean;detectUrl:boolean;detectJwt:boolean;neverStoreClipboard:boolean;clearAfterProcessing:boolean;language:string}
type PaletteItem = {id:string;labelKey:string;groupKey:string;icon:Icon;keywords:string;page?:Page;tool?:ToolId;action?:string;needsInput?:boolean}
type TranslatablePaletteItem = PaletteItem & {label:string;group:string}
type IndexedItem = TranslatablePaletteItem & {text:string;pinyin:string;initials:string}
const defaultSettings: Settings = {clipboardDetection:true,analyzeOnOpen:true,detectJson:true,detectTimestamp:true,detectUrl:true,detectJwt:true,neverStoreClipboard:true,clearAfterProcessing:false,language:'zh-CN'}
const tools = [
  {id:'json' as const,nameKey:'tools.json.name',descriptionKey:'tools.json.description',icon:BracketsCurly,keywords:'json format minify compare schema path'},
  {id:'time' as const,nameKey:'tools.time.name',descriptionKey:'tools.time.description',icon:Clock,keywords:'time timestamp date unix utc rfc iso'},
  {id:'text' as const,nameKey:'tools.text.name',descriptionKey:'tools.text.description',icon:TextT,keywords:'text count trim spaces lines bytes'},
]
const paletteItems: PaletteItem[] = [
  {id:'nav:home',labelKey:'nav.home',groupKey:'groups.nav',icon:House,keywords:'home start dashboard 首页 回到主页',page:'home'},
  {id:'nav:settings',labelKey:'nav.settings',groupKey:'groups.nav',icon:GearSix,keywords:'settings preferences options 设置 配置 选项',page:'settings'},
  {id:'nav:history',labelKey:'nav.history',groupKey:'groups.nav',icon:ClockCounterClockwise,keywords:'history recent log activity 历史 记录',page:'history'},
  {id:'open:json',labelKey:'commands.openJson',groupKey:'groups.tools',icon:BracketsCurly,keywords:'json workspace 打开工具',page:'json'},
  {id:'open:time',labelKey:'commands.openTime',groupKey:'groups.tools',icon:Clock,keywords:'time timestamp date 时间 打开工具',page:'time'},
  {id:'open:text',labelKey:'commands.openText',groupKey:'groups.tools',icon:TextT,keywords:'text toolkit 文本 打开工具',page:'text'},
  {id:'json:format',labelKey:'commands.format',groupKey:'groups.json',icon:BracketsCurly,keywords:'format pretty indent beautify 格式化 美化',tool:'json',action:'format',needsInput:true},
  {id:'json:minify',labelKey:'commands.minify',groupKey:'groups.json',icon:BracketsCurly,keywords:'minify compact uglify 压缩 精简 缩小',tool:'json',action:'minify',needsInput:true},
  {id:'json:validate',labelKey:'commands.validate',groupKey:'groups.json',icon:BracketsCurly,keywords:'validate check verify lint 校验 检查 验证',tool:'json',action:'validate',needsInput:true},
  {id:'time:convert',labelKey:'commands.convert',groupKey:'groups.time',icon:Clock,keywords:'timestamp convert unix seconds 时间戳 转换',tool:'time',action:'convert',needsInput:true},
  {id:'text:trim',labelKey:'commands.trim',groupKey:'groups.text',icon:TextT,keywords:'trim whitespace 修剪 去除首尾空白',tool:'text',action:'trim',needsInput:true},
  {id:'text:removeSpaces',labelKey:'commands.removeSpaces',groupKey:'groups.text',icon:TextT,keywords:'remove spaces 删除 空格',tool:'text',action:'removeSpaces',needsInput:true},
  {id:'text:compress',labelKey:'commands.compress',groupKey:'groups.text',icon:TextT,keywords:'compress whitespace collapse 压缩 合并空白',tool:'text',action:'compress',needsInput:true},
  {id:'text:count',labelKey:'commands.count',groupKey:'groups.text',icon:TextT,keywords:'count characters words lines 统计 字数 行数 字节',tool:'text',action:'count',needsInput:true},
]
function loadValue<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}}
function formatRelative(date:string,t:(k:string,o?:Record<string,unknown>)=>string){const minutes=Math.max(0,Math.round((Date.now()-new Date(date).getTime())/60000));if(minutes<1)return t('timeAgo.justNow');if(minutes<60)return t('timeAgo.minutes',{count:minutes});const hours=Math.round(minutes/60);return hours<24?t('timeAgo.hours',{count:hours}):t('timeAgo.days',{count:Math.round(hours/24)})}
function fuzzyScore(text:string,q:string):number{let m=0,score=0,streak=0,prev=-1;for(let i=0;i<q.length;i++){const idx=text.indexOf(q[i],m);if(idx<0)return -1;if(prev!==-1&&idx===prev+1){streak++;score+=3+streak*2}else{streak=0;score+=1+(idx===0?4:0)}prev=idx;m=idx+1}return score+(m===text.length?2:0)}
function buildIndex(items:TranslatablePaletteItem[]):IndexedItem[]{return items.map(item=>{const text=(`${item.label} ${item.keywords}`).toLowerCase().replace(/\s+/g,'');let initials='';for(const c of text){if(/[\u4e00-\u9fff]/.test(c)){const s=pinyin(c,{toneType:'none',type:'array'})[0]??'';if(s)initials+=s[0]}else if(/[a-z0-9]/.test(c))initials+=c}return{...item,text,pinyin:pinyin(text,{toneType:'none',type:'array'}).join('').replace(/\s+/g,'').toLowerCase(),initials}})}


function App(){
  const{t,i18n}=useTranslation();const workspaceRef=useRef<HTMLElement>(null)
  const[page,setPage]=useState<Page>('home');const[paletteOpen,setPaletteOpen]=useState(false);const[pending,setPending]=useState<PendingAction|null>(null);const[favorites,setFavorites]=useState<ToolId[]>(()=>loadValue('devutils.favorites',['json']));const[history,setHistory]=useState<HistoryItem[]>(()=>loadValue('devutils.history',[]));const[settings,setSettings]=useState<Settings>(()=>loadValue('devutils.settings',defaultSettings))
  useEffect(()=>{if(settings.language&&i18n.language!==settings.language)i18n.changeLanguage(settings.language)},[i18n,settings.language])
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setPaletteOpen(open=>!open)}else if(event.key==='Escape'){if(paletteOpen)setPaletteOpen(false);else setPage('home')}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[paletteOpen])
  useEffect(()=>Events.On('navigate',event=>setPage(event.data as Page)),[])
  useEffect(()=>Events.On('tray:analyze',()=>{void analyzeClipboard()}),[settings])
  useEffect(()=>workspaceRef.current?.scrollTo(0,0),[page])
  useEffect(()=>localStorage.setItem('devutils.favorites',JSON.stringify(favorites)),[favorites]);useEffect(()=>localStorage.setItem('devutils.history',JSON.stringify(history)),[history]);useEffect(()=>localStorage.setItem('devutils.settings',JSON.stringify(settings)),[settings])
  const indexed=useMemo(()=>buildIndex(paletteItems.map(item=>({...item,label:t(item.labelKey),group:t(item.groupKey)}))),[t])
  const record=(tool:ToolId,action:string,detail:string)=>setHistory(current=>[{id:Date.now(),tool,action,detail,at:new Date().toISOString()},...current].slice(0,50));const openTool=(id:ToolId)=>{setPage(id);setPending(null)}
  const run=(item:IndexedItem)=>{setPaletteOpen(false);if(!item.tool){setPending(null);setPage(item.page??'home');return}const tool=item.tool;const action=item.action??'open';const needsInput=!!item.needsInput;const apply=async()=>{let input='';if(needsInput){input=(await Clipboard.Text().catch(()=>''))||'';if(!input.trim()){setPending(null);setPage(tool);toast(t('toast.clipboardEmpty'),{description:t('toast.clipboardEmptyDesc'),variant:'warning'});return}}setPending({tool,action,input});setPage(tool)};apply()}
  const analyzeClipboard=async()=>{if(!settings.clipboardDetection||!settings.analyzeOnOpen)return;const text=(await Clipboard.Text().catch(()=>''))||'';const s=text.trim();if(!s)return;let tool:ToolId|null=null;if(settings.detectJson){try{parseJsonLoose(s);tool='json'}catch{}}if(!tool&&settings.detectTimestamp&&(/^\d{10,13}$/.test(s)||(/[\s\-/:T]/.test(s)&&!Number.isNaN(new Date(s).getTime()))))tool='time';if(!tool&&settings.detectJwt&&/^eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(s))tool='text';if(!tool&&settings.detectUrl&&/^[a-z][a-z0-9+.-]*:\/\/\S+/i.test(s))tool='text';if(tool){setPending({tool,action:'open',input:text});setPage(tool)}}
  return <>
    <ToastProvider placement="bottom"/>
    <div className="app-shell dark">
      <div className="ambient"/>
      <div className="main"><Sidebar page={page} onNavigate={setPage} onOpenPalette={()=>setPaletteOpen(true)}/><main className="workspace" ref={workspaceRef}>{page==='home'&&<Home favorites={favorites} history={history} openTool={openTool} toggleFavorite={id=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/>} <div className={`tool-slot fill${page==='json'?'':' hidden'}`}><JsonTool active={page==='json'} record={record} pending={pending} clearPending={()=>setPending(null)}/></div><div className={`tool-slot${page==='time'?'':' hidden'}`}><TimeTool active={page==='time'} record={record} pending={pending} clearPending={()=>setPending(null)}/></div><div className={`tool-slot${page==='text'?'':' hidden'}`}><TextTool active={page==='text'} record={record} pending={pending} clearPending={()=>setPending(null)}/></div> {page==='settings'&&<SettingsPage settings={settings} setSettings={setSettings} clearHistory={()=>setHistory([])}/>} {page==='history'&&<HistoryPage history={history} openTool={openTool} clear={()=>setHistory([])}/>}</main></div>
      <CommandPalette open={paletteOpen} onClose={()=>setPaletteOpen(false)} indexed={indexed} run={run}/>
    </div>
  </>
}

function CommandPalette({open,onClose,indexed,run}:{open:boolean;onClose:()=>void;indexed:IndexedItem[];run:(item:IndexedItem)=>void}){
  const{t}=useTranslation();const[input,setInput]=useState('');const[active,setActive]=useState(0)
  useEffect(()=>{if(open){setInput('');setActive(0)}},[open])
  const matches=useMemo(()=>{const q=input.trim().toLowerCase().replace(/\s+/g,'');if(!q)return null;const scored:Array<{item:IndexedItem;score:number}>=[];for(const item of indexed){const score=Math.max(fuzzyScore(item.text,q),fuzzyScore(item.pinyin,q)*.95,fuzzyScore(item.initials,q)*.9);if(score>0)scored.push({item,score})}scored.sort((a,b)=>b.score-a.score);return scored.map(s=>s.item)},[input,indexed])
  const list=matches??indexed
  useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(a=>list.length?Math.min(a+1,list.length-1):0)}else if(e.key==='ArrowUp'){e.preventDefault();setActive(a=>list.length?Math.max(a-1,0):0)}else if(e.key==='Enter'){e.preventDefault();const item=list[active];if(item)run(item)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[open,active,list])
  if(!open)return null
  return <div className="palette-backdrop" onClick={onClose}><div className="palette-card" onClick={event=>event.stopPropagation()}><div className="palette-input"><MagnifyingGlass size={18} weight="bold"/><input autoFocus role="combobox" aria-expanded={list.length>0} aria-controls="palette-listbox" aria-activedescendant={list.length?`palette-opt-${active}`:undefined} aria-label={t('palette.searchLabel')} value={input} onChange={e=>{setInput(e.target.value);setActive(0)}} placeholder={t('palette.searchPlaceholder')}/></div>{list.length>0?<div className="palette-list" id="palette-listbox" role="listbox" aria-label={t('palette.listLabel')}>{list.map((item,i)=><button key={item.id} id={`palette-opt-${i}`} role="option" aria-selected={i===active} className={`palette-row${i===active?' active':''}`} onMouseEnter={()=>setActive(i)} onClick={()=>run(item)}><span className="palette-item"><item.icon size={16} weight="bold"/><span className="palette-label">{t(item.labelKey)}</span><small>{t(item.groupKey)}</small></span></button>)}</div>:<div className="palette-list palette-empty" role="status"><span>{t('palette.empty')}</span></div>}</div></div>
}

function Sidebar({page,onNavigate,onOpenPalette}:{page:Page;onNavigate:(p:Page)=>void;onOpenPalette:()=>void}){const{t}=useTranslation();return <aside className="sidebar"><div className="sidebar-drag" aria-hidden/><nav aria-label={t('groups.tools')}><div className="sidebar-heading">{t('groups.tools')}</div>{tools.map(tool=><button key={tool.id} className={`sidebar-item${page===tool.id?' active':''}`} aria-current={page===tool.id?'page':undefined} onClick={()=>onNavigate(tool.id)}><tool.icon size={17} weight="bold"/><span>{t(tool.nameKey)}</span></button>)}</nav><nav aria-label={t('titlebar.nav')}><div className="sidebar-heading">{t('titlebar.nav')}</div><button className={`sidebar-item${page==='history'?' active':''}`} aria-current={page==='history'?'page':undefined} onClick={()=>onNavigate('history')}><ClockCounterClockwise size={17} weight="bold"/><span>{t('titlebar.history')}</span></button><button className={`sidebar-item${page==='settings'?' active':''}`} aria-current={page==='settings'?'page':undefined} onClick={()=>onNavigate('settings')}><GearSix size={17} weight="bold"/><span>{t('titlebar.settings')}</span></button></nav><div className="sidebar-footer"><button className="sidebar-palette" onClick={onOpenPalette}><kbd>{navigator.platform.includes('Mac')?'⌘':'Ctrl'}</kbd><kbd>K</kbd><span>{t('statusbar.openPalette')}</span></button></div></aside>}
function Home({favorites,history,openTool,toggleFavorite}:{favorites:ToolId[];history:HistoryItem[];openTool:(id:ToolId)=>void;toggleFavorite:(id:ToolId)=>void}){const{t}=useTranslation();return <section className="home-page">{history.length>0&&<Reveal index={0}><section className="recent-strip"><div className="section-heading"><span>{t('home.recent')}</span><span>{t('home.lastActions')}</span></div>{history.slice(0,2).map((item,idx)=><button key={item.id} className="recent-row" style={{'--index':idx} as React.CSSProperties} onClick={()=>openTool(item.tool)}><span className="recent-icon">{item.tool==='json'?<BracketsCurly weight="bold"/>:item.tool==='time'?<Clock weight="bold"/>:<TextT weight="bold"/>}</span><span><strong>{item.action}</strong><small>{item.detail}</small></span><time>{formatRelative(item.at,t)}</time><CaretRight size={14} weight="bold"/></button>)}</section></Reveal>}<Reveal index={1}><ToolSection title={t('home.tools')} subtitle={t('home.subtitle')} toolsToShow={tools} favorites={favorites} openTool={openTool} toggleFavorite={toggleFavorite}/></Reveal></section>}
function ToolSection({title,subtitle,toolsToShow,favorites,openTool,toggleFavorite}:{title:string;subtitle:string;toolsToShow:typeof tools;favorites:ToolId[];openTool:(id:ToolId)=>void;toggleFavorite:(id:ToolId)=>void}){const{t}=useTranslation();return <section className="tool-list"><div className="section-heading"><span>{title}</span><span>{subtitle}</span></div>{toolsToShow.map((tool,index)=><div className="tool-row" key={tool.id} style={{'--index':index} as React.CSSProperties}><button className="tool-main" onClick={()=>openTool(tool.id)}><span className="tool-icon"><tool.icon size={21} weight="bold"/></span><span><strong>{t(tool.nameKey)}</strong><small>{t(tool.descriptionKey)}</small></span></button><button className={`favorite ${favorites.includes(tool.id)?'selected':''}`} onClick={()=>toggleFavorite(tool.id)} aria-label={favorites.includes(tool.id)?t('home.removeFavorite'):t('home.addFavorite')}><Heart size={16} weight={favorites.includes(tool.id)?'fill':'bold'}/></button><CaretRight className="row-caret" size={16} weight="bold"/></div>)}</section>}
function SettingsPage({settings,setSettings,clearHistory}:{settings:Settings;setSettings:React.Dispatch<React.SetStateAction<Settings>>;clearHistory:()=>void}){const{t}=useTranslation();const update=(key:keyof Settings,value:boolean)=>setSettings(current=>({...current,[key]:value}));const setLanguage=(code:string)=>{setSettings(current=>({...current,language:code}));i18n.changeLanguage(code)};return <Reveal index={0}><section className="settings-page"><header className="page-title"><h1>{t('settings.title')}</h1><p>{t('settings.subtitle')}</p></header><SettingsGroup title={t('settings.language')} subtitle={t('settings.languageSubtitle')}><Setting label={t(`settings.languages.${settings.language}`)}><div className="segmented language-switch">{SUPPORTED_LANGUAGES.map(l=><button key={l.code} className={settings.language===l.code?'active':''} onClick={()=>setLanguage(l.code)}>{t(l.labelKey)}</button>)}</div></Setting></SettingsGroup><SettingsGroup title={t('settings.clipboard')} subtitle={t('settings.clipboardSubtitle')}><Setting label={t('settings.enableDetection')} description={t('settings.enableDetectionDesc')}><Switch isSelected={settings.clipboardDetection} onChange={v=>update('clipboardDetection',v)}/></Setting><Setting label={t('settings.analyzeOnOpen')} description={t('settings.analyzeOnOpenDesc')}><Switch isSelected={settings.analyzeOnOpen} onChange={v=>update('analyzeOnOpen',v)}/></Setting></SettingsGroup><SettingsGroup title={t('settings.detection')} subtitle={t('settings.detectionSubtitle')}>{([['detectJson',t('types.json')],['detectTimestamp',t('types.timestamp')],['detectUrl',t('types.url')],['detectJwt',t('types.jwt')]] as [Exclude<keyof Settings,'language'>,string][]).map(([key,label])=><Setting key={key} label={label}><Switch isSelected={settings[key]} onChange={v=>update(key,v)}/></Setting>)}</SettingsGroup><SettingsGroup title={t('settings.privacy')} subtitle={t('settings.privacySubtitle')}><Setting label={t('settings.neverStore')} description={t('settings.neverStoreDesc')}><Switch isSelected={settings.neverStoreClipboard} onChange={v=>update('neverStoreClipboard',v)}/></Setting><Setting label={t('settings.clearAfter')} description={t('settings.clearAfterDesc')}><Switch isSelected={settings.clearAfterProcessing} onChange={v=>update('clearAfterProcessing',v)}/></Setting><Setting label={t('settings.history')} description={t('settings.historyDesc')}><Button variant="danger-soft" onPress={clearHistory}><Trash weight="bold"/>{t('settings.clearHistory')}</Button></Setting></SettingsGroup></section></Reveal>}
function SettingsGroup({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="settings-group"><div><h2>{title}</h2><p>{subtitle}</p></div><div className="settings-list">{children}</div></section>}
function Setting({label,description,children}:{label:string;description?:string;children:React.ReactNode}){return <div className="setting"><span><strong>{label}</strong>{description&&<small>{description}</small>}</span>{children}</div>}
function HistoryPage({history,openTool,clear}:{history:HistoryItem[];openTool:(id:ToolId)=>void;clear:()=>void}){const{t}=useTranslation();return <Reveal index={0}><section className="history-page"><header className="page-title row"><div><h1>{t('history.title')}</h1><p>{t('history.subtitle')}</p></div>{history.length>0&&<Button variant="tertiary" onPress={clear}><Trash weight="bold"/>{t('history.clear')}</Button>}</header>{history.length?<div className="history-list">{history.map((item,idx)=><button key={item.id} style={{'--index':idx} as React.CSSProperties} onClick={()=>openTool(item.tool)}><span className="history-tool">{item.tool==='json'?<BracketsCurly weight="bold"/>:item.tool==='time'?<Clock weight="bold"/>:<TextT weight="bold"/>}</span><span><strong>{item.action}</strong><small>{item.detail}</small></span><time>{formatRelative(item.at,t)}</time><CaretRight weight="bold"/></button>)}</div>:<div className="empty-state history-empty"><Hash size={28} weight="bold"/><strong>{t('history.emptyTitle')}</strong><span>{t('history.emptyHint')}</span></div>}</section></Reveal>}
export default App
