import {useEffect, useLayoutEffect, useMemo, useRef, useState} from 'react'
import {AlertDialog, Button, Switch} from '@heroui/react'
import {Clipboard, Events} from '@wailsio/runtime'
import {useTranslation} from 'react-i18next'
import {pinyin} from 'pinyin-pro'
import {ArrowLeft, ArrowRight, BracketsCurly, CaretRight, ClipboardText, Clock, ClockCounterClockwise, FileCode, GearSix, GitDiff, Hash, Heart, House, MagnifyingGlass, SidebarSimple, TextT, Trash} from '@phosphor-icons/react'
import i18n, {SUPPORTED_LANGUAGES} from './i18n'
import JsonTool from './components/JsonTool'
import TimeTool from './components/TimeTool'
import TextTool from './components/TextTool'
import Base64Tool from './components/Base64Tool'
import DiffTool, {type HighlightMode} from './components/DiffTool'
import {parseJsonLoose, Reveal, type Icon, type PendingAction, type ToolId} from './components/shared'
import {parseTimeInput} from './utils/time'
import {AppToastProvider, toast} from './components/AppToast'
import {AppendHistory, ClearHistory, Get as GetConfig, GetHistoryContent, GetHistoryPage, Save as SaveConfig} from '../bindings/changeme/configservice'
import type {Config as Settings, HistoryItem as StoredHistoryItem} from '../bindings/changeme/models'

type Page = 'home' | 'settings' | 'history' | ToolId
type SidebarMode = 'full' | 'icon' | 'hidden'
type BooleanSettingKey = 'trayMatchEnabled'|'autoOverwrite'
type HistoryItem = Omit<StoredHistoryItem,'tool'> & {tool:ToolId}
type PaletteItem = {id:string;labelKey:string;groupKey:string;icon:Icon;keywords:string;page?:Page;tool?:ToolId;action?:string;mode?:string;target?:'before'|'after'|'alternate';subgroupKey?:string;needsInput?:boolean;whenSortOpen?:boolean}
type TranslatablePaletteItem = PaletteItem & {label:string;group:string;subgroup:string}
type IndexedItem = TranslatablePaletteItem & {text:string;pinyin:string;initials:string}
const defaultSettings: Settings = {trayMatchEnabled:true,autoOverwrite:true,language:'zh-CN',sidebarMode:'full',theme:'dark',diffHighlightMode:'character',diffClipboardTargetMode:'alternate',codeEditorFontSize:12}
const tools = [
  {id:'json' as const,nameKey:'tools.json.name',descriptionKey:'tools.json.description',icon:BracketsCurly,keywords:'json format minify compare schema path'},
  {id:'time' as const,nameKey:'tools.time.name',descriptionKey:'tools.time.description',icon:Clock,keywords:'time timestamp date unix utc rfc iso'},
  {id:'text' as const,nameKey:'tools.text.name',descriptionKey:'tools.text.description',icon:TextT,keywords:'text count trim spaces lines bytes'},
  {id:'base64' as const,nameKey:'tools.base64.name',descriptionKey:'tools.base64.description',icon:FileCode,keywords:'base64 encode decode text image data url 图片 编码 解码'},
  {id:'diff' as const,nameKey:'tools.diff.name',descriptionKey:'tools.diff.description',icon:GitDiff,keywords:'diff compare patch code text difference 差异 对比 比较'},
]
const paletteItems: PaletteItem[] = [
  {id:'nav:home',labelKey:'nav.home',groupKey:'groups.nav',icon:House,keywords:'home start dashboard 首页 回到主页',page:'home'},
  {id:'nav:settings',labelKey:'nav.settings',groupKey:'groups.nav',icon:GearSix,keywords:'settings preferences options 设置 配置 选项',page:'settings'},
  {id:'nav:history',labelKey:'nav.history',groupKey:'groups.nav',icon:ClockCounterClockwise,keywords:'history recent log activity 历史 记录',page:'history'},
  {id:'open:json',labelKey:'commands.openJson',groupKey:'groups.tools',icon:BracketsCurly,keywords:'json workspace 打开工具',page:'json'},
  {id:'open:time',labelKey:'commands.openTime',groupKey:'groups.tools',icon:Clock,keywords:'time timestamp date 时间 打开工具',page:'time'},
  {id:'open:text',labelKey:'commands.openText',groupKey:'groups.tools',icon:TextT,keywords:'text toolkit 文本 打开工具',page:'text'},
  {id:'open:base64',labelKey:'commands.openBase64',groupKey:'groups.tools',icon:FileCode,keywords:'base64 图片 文本 编码 解码 打开工具',page:'base64'},
  {id:'open:diff',labelKey:'commands.openDiff',groupKey:'groups.tools',icon:GitDiff,keywords:'diff compare patch code text 差异 对比 比较 打开工具',page:'diff'},
  {id:'paste',labelKey:'commands.paste',groupKey:'groups.tools',icon:ClipboardText,keywords:'paste clipboard insert zhantie niantie 粘贴 剪贴板 插入',action:'paste'},
  {id:'json:format',labelKey:'jsonTool.format',groupKey:'tools.json.name',icon:BracketsCurly,keywords:'format pretty indent beautify 格式化 美化',tool:'json',action:'format'},
  {id:'json:minify',labelKey:'jsonTool.minify',groupKey:'tools.json.name',icon:BracketsCurly,keywords:'minify compact uglify 压缩 精简 缩小',tool:'json',action:'minify'},
  {id:'json:copy',labelKey:'jsonTool.copy',groupKey:'tools.json.name',icon:BracketsCurly,keywords:'copy json clipboard 复制 拷贝 剪贴板',tool:'json',action:'copy'},
  {id:'json:clear',labelKey:'jsonTool.clear',groupKey:'tools.json.name',icon:BracketsCurly,keywords:'clear reset empty 清空 重置',tool:'json',action:'clear'},
  {id:'json:sortRules',labelKey:'commands.toggleSortRules',groupKey:'tools.json.name',icon:BracketsCurly,keywords:'sort rules advanced panel 切换 排序 规则 高级 面板',tool:'json',action:'sort'},
  {id:'json:sortAddRule',labelKey:'jsonTool.sortAddRule',groupKey:'tools.json.name',icon:BracketsCurly,keywords:'sort add rule append 排序 添加 规则 追加',tool:'json',action:'sortAddRule',whenSortOpen:true},
  {id:'json:sortApply',labelKey:'jsonTool.sortApply',groupKey:'tools.json.name',icon:BracketsCurly,keywords:'sort apply execute run 排序 执行 应用',tool:'json',action:'sortApply',whenSortOpen:true},
  {id:'json:sortRestore',labelKey:'jsonTool.sortRestore',groupKey:'tools.json.name',icon:BracketsCurly,keywords:'sort restore undo reset original 排序 还原 恢复 撤销 原始',tool:'json',action:'sortDefault',whenSortOpen:true},
  {id:'json:schema',labelKey:'commands.toggleSchema',groupKey:'tools.json.name',icon:BracketsCurly,keywords:'schema jsonpath path panel 切换 结构 路径 面板 侧栏',tool:'json',action:'schema'},
  {id:'time:refresh',labelKey:'timeTool.refresh',groupKey:'tools.time.name',icon:Clock,keywords:'time timestamp now refresh 时间戳 当前 插入 刷新',tool:'time',action:'refresh'},
  {id:'time:timezone',labelKey:'timeTool.useSystemTimezone',groupKey:'tools.time.name',icon:Clock,keywords:'time timezone system local 时区 系统 本机',tool:'time',action:'timezone'},
  {id:'text:clear',labelKey:'textTool.clear',groupKey:'tools.text.name',icon:TextT,keywords:'clear reset empty 清空 重置',tool:'text',action:'clear'},
  {id:'text:trim',labelKey:'textTool.trim',groupKey:'tools.text.name',icon:TextT,keywords:'trim whitespace 修剪 去除首尾空白',tool:'text',action:'trim'},
  {id:'text:removeSpaces',labelKey:'textTool.removeSpaces',groupKey:'tools.text.name',icon:TextT,keywords:'remove spaces 删除 空格',tool:'text',action:'removeSpaces'},
  {id:'text:compress',labelKey:'textTool.compressSpaces',groupKey:'tools.text.name',icon:TextT,keywords:'compress spaces collapse 修剪 空格',tool:'text',action:'compress'},
  {id:'text:compressLine',labelKey:'textTool.compressLine',groupKey:'tools.text.name',icon:TextT,keywords:'line newline one line 压缩 换行 一行',tool:'text',action:'compressLine'},
  {id:'text:upper',labelKey:'textTool.caseModes.upper',groupKey:'tools.text.name',subgroupKey:'textTool.case',icon:TextT,keywords:'uppercase case 大写 转换',tool:'text',action:'upper'},
  {id:'text:lower',labelKey:'textTool.caseModes.lower',groupKey:'tools.text.name',subgroupKey:'textTool.case',icon:TextT,keywords:'lowercase case 小写 转换',tool:'text',action:'lower'},
  {id:'text:lineUpper',labelKey:'textTool.caseModes.lineUpper',groupKey:'tools.text.name',subgroupKey:'textTool.case',icon:TextT,keywords:'line case upper 行首 大写 转换',tool:'text',action:'lineUpper'},
  {id:'text:lineLower',labelKey:'textTool.caseModes.lineLower',groupKey:'tools.text.name',subgroupKey:'textTool.case',icon:TextT,keywords:'line case lower 行首 小写 转换',tool:'text',action:'lineLower'},
  {id:'text:wordUpper',labelKey:'textTool.caseModes.wordUpper',groupKey:'tools.text.name',subgroupKey:'textTool.case',icon:TextT,keywords:'word case upper 词首 单词 大写 转换',tool:'text',action:'wordUpper'},
  {id:'text:wordLower',labelKey:'textTool.caseModes.wordLower',groupKey:'tools.text.name',subgroupKey:'textTool.case',icon:TextT,keywords:'word case lower 词首 单词 小写 转换',tool:'text',action:'wordLower'},
  {id:'base64:clear',labelKey:'base64Tool.clear',groupKey:'tools.base64.name',icon:FileCode,keywords:'clear reset empty 清空 重置',tool:'base64',action:'clear'},
  {id:'base64:copy',labelKey:'base64Tool.copy',groupKey:'tools.base64.name',icon:FileCode,keywords:'copy base64 clipboard result 复制 拷贝 剪贴板 结果',tool:'base64',action:'copy'},
  {id:'diff:swap',labelKey:'diffTool.swap',groupKey:'tools.diff.name',icon:GitDiff,keywords:'swap exchange 交换 对调',tool:'diff',action:'swap'},
  {id:'diff:clear',labelKey:'diffTool.clear',groupKey:'tools.diff.name',icon:GitDiff,keywords:'clear reset 清空 重置',tool:'diff',action:'clear'},
  {id:'diff:highlightWordAlt',labelKey:'diffTool.modes.word-alt',groupKey:'tools.diff.name',subgroupKey:'diffTool.highlightMode',icon:GitDiff,keywords:'highlight mode word alt 高亮 按词 交替',tool:'diff',action:'highlight',mode:'word-alt'},
  {id:'diff:highlightWord',labelKey:'diffTool.modes.word',groupKey:'tools.diff.name',subgroupKey:'diffTool.highlightMode',icon:GitDiff,keywords:'highlight mode word 高亮 按词',tool:'diff',action:'highlight',mode:'word'},
  {id:'diff:highlightCharacter',labelKey:'diffTool.modes.character',groupKey:'tools.diff.name',subgroupKey:'diffTool.highlightMode',icon:GitDiff,keywords:'highlight mode character 高亮 按字符 逐字',tool:'diff',action:'highlight',mode:'character'},
  {id:'diff:highlightNone',labelKey:'diffTool.modes.none',groupKey:'tools.diff.name',subgroupKey:'diffTool.highlightMode',icon:GitDiff,keywords:'highlight mode none off 高亮 关闭',tool:'diff',action:'highlight',mode:'none'},
  {id:'diff:fillAlternate',labelKey:'diffTool.targets.alternate',groupKey:'tools.diff.name',subgroupKey:'diffTool.clipboardTarget',icon:GitDiff,keywords:'clipboard fill alternate 剪贴板 填入 交替',tool:'diff',action:'fill',target:'alternate',needsInput:true},
  {id:'diff:fillBefore',labelKey:'diffTool.targets.before',groupKey:'tools.diff.name',subgroupKey:'diffTool.clipboardTarget',icon:GitDiff,keywords:'clipboard fill before 剪贴板 填入 原始 内容',tool:'diff',action:'fill',target:'before',needsInput:true},
  {id:'diff:fillAfter',labelKey:'diffTool.targets.after',groupKey:'tools.diff.name',subgroupKey:'diffTool.clipboardTarget',icon:GitDiff,keywords:'clipboard fill after 剪贴板 填入 修改 内容',tool:'diff',action:'fill',target:'after',needsInput:true},
]
function loadValue<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}}
function formatRelative(date:string,t:(k:string,o?:Record<string,unknown>)=>string){const minutes=Math.max(0,Math.round((Date.now()-new Date(date).getTime())/60000));if(minutes<1)return t('timeAgo.justNow');if(minutes<60)return t('timeAgo.minutes',{count:minutes});const hours=Math.round(minutes/60);return hours<24?t('timeAgo.hours',{count:hours}):t('timeAgo.days',{count:Math.round(hours/24)})}
function normalizeHistoryDetail(detail:string){return detail.replace(/\s+/g,' ').trim()}
function toHistoryItem(item:StoredHistoryItem):HistoryItem|null{return item.tool==='json'||item.tool==='time'||item.tool==='text'||item.tool==='base64'||item.tool==='diff'?{...item,tool:item.tool,detail:normalizeHistoryDetail(item.detail)}:null}
function pageFromLocation():Page{const path=window.location.pathname.replace(/^\/+/,''),hash=window.location.hash.replace(/^#\/?/,'');const value=path||hash;if(value==='home'||value==='settings'||value==='history'||tools.some(tool=>tool.id===value))return value as Page;return 'home'}
function detectBase64(s:string):'text'|'image'|null{const data=/^data:[^,]+;base64,([A-Za-z0-9+/_=-]+)$/i.exec(s);const raw=(data?.[1]??s).replace(/\s/g,'');const explicit=data!==null||raw.includes('=');if(raw.length>16*1024*1024||raw.includes('.')||(!explicit&&raw.length<16)||!/^[A-Za-z0-9+/_-]+={0,2}$/.test(raw))return null;const padded=raw.replace(/-/g,'+').replace(/_/g,'/');if(padded.length%4===1)return null;try{const bytes=Uint8Array.from(atob(padded.padEnd(Math.ceil(padded.length/4)*4,'=')),c=>c.charCodeAt(0));const image=bytes.length>8&&((bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)||(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)||String.fromCharCode(...bytes.slice(0,6)).startsWith('GIF')||String.fromCharCode(...bytes.slice(8,12))==='WEBP');return image?'image':'text'}catch{return null}}
function fuzzyScore(text:string,q:string):number{let m=0,score=0,streak=0,prev=-1;for(let i=0;i<q.length;i++){const idx=text.indexOf(q[i],m);if(idx<0)return -1;if(prev!==-1&&idx===prev+1){streak++;score+=3+streak*2}else{streak=0;score+=1+(idx===0?4:0)}prev=idx;m=idx+1}return score+(m===text.length?2:0)}
function buildIndex(items:TranslatablePaletteItem[]):IndexedItem[]{return items.map(item=>{const text=(`${item.label} ${item.group} ${item.subgroup} ${item.keywords}`).toLowerCase().replace(/\s+/g,'');let initials='';for(const c of text){if(/[\u4e00-\u9fff]/.test(c)){const s=pinyin(c,{toneType:'none',type:'array'})[0]??'';if(s)initials+=s[0]}else if(/[a-z0-9]/.test(c))initials+=c}return{...item,text,pinyin:pinyin(text,{toneType:'none',type:'array'}).join('').replace(/\s+/g,'').toLowerCase(),initials}})}


function App(){
  const{ t,i18n}=useTranslation();const workspaceRef=useRef<HTMLElement>(null)
  const initialPage=pageFromLocation();const[page,setPage]=useState<Page>(initialPage);const pageRef=useRef<Page>(initialPage);const[paletteOpen,setPaletteOpen]=useState(false);const[pending,setPending]=useState<PendingAction|null>(null);const[jsonSortOpen,setJsonSortOpen]=useState(false);const[matchDialog,setMatchDialog]=useState<null|{tool:ToolId;input:string;mode?:string;target?:'before'|'after'}>(null);const[favorites,setFavorites]=useState<ToolId[]>(()=>loadValue('devutils.favorites',['json']));const[history,setHistory]=useState<HistoryItem[]>([]);const[settings,setSettings]=useState<Settings>(defaultSettings);const nextDiffTarget=useRef<'before'|'after'>('before');const settingsReady=useRef(false);const historyReady=useRef(false);const lastFocusedRef=useRef<Element|null>(null);const theme=settings.theme==='light'?'light':'dark'
  const navigate=(next:Page)=>{if(next===pageRef.current)return;window.history.pushState({page:next},'',`/${next}`);pageRef.current=next;setPage(next)}
  useEffect(()=>{const root=document.documentElement;root.classList.remove('light','dark');root.classList.add(theme);root.dataset.theme=theme;root.style.setProperty('--code-editor-font-size',`${settings.codeEditorFontSize||12}px`)},[theme,settings.codeEditorFontSize])
  useEffect(()=>{if(settings.language&&i18n.language!==settings.language)i18n.changeLanguage(settings.language)},[i18n,settings.language])
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if(!paletteOpen)lastFocusedRef.current=document.activeElement;setPaletteOpen(open=>!open)}else if(event.key==='Escape'&&paletteOpen)setPaletteOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[paletteOpen])
  useEffect(()=>Events.On('navigate',event=>navigate(event.data as Page)),[])
  useEffect(()=>{const onPopState=()=>{const next=pageFromLocation();pageRef.current=next;setPage(next)};window.addEventListener('popstate',onPopState);return()=>window.removeEventListener('popstate',onPopState)},[])
  useEffect(()=>{const onMouseDown=(event:MouseEvent)=>{if(event.button!==3&&event.button!==4)return;event.preventDefault();if(event.button===3)window.history.back();else window.history.forward()};window.addEventListener('mousedown',onMouseDown,true);return()=>window.removeEventListener('mousedown',onMouseDown,true)},[])
  useEffect(()=>{const next=pageFromLocation();window.history.replaceState({page:next},'',`/${next}`);pageRef.current=next;setPage(next)},[])
  useEffect(()=>Events.On('tray:analyze',()=>{void analyzeClipboard()}),[settings])
  useLayoutEffect(()=>workspaceRef.current?.scrollTo(0,0),[page])
  useEffect(()=>{GetConfig().then(c=>{settingsReady.current=true;setSettings(c)}).catch(()=>{settingsReady.current=true})},[])
  useEffect(()=>{if(!settingsReady.current)return;void SaveConfig(settings)},[settings])
  useEffect(()=>{GetHistoryPage(0,10).then(page=>{historyReady.current=true;setHistory((page.items??[]).map(toHistoryItem).filter((x):x is HistoryItem=>x!==null))}).catch(()=>{historyReady.current=true})},[])
  useEffect(()=>localStorage.setItem('devutils.favorites',JSON.stringify(favorites)),[favorites])
  const sidebarMode=(settings.sidebarMode as SidebarMode)||'full'
  const indexed=useMemo(()=>{const items=paletteItems.filter(item=>!item.whenSortOpen||(jsonSortOpen&&page==='json'));return buildIndex(items.map(item=>({...item,label:t(item.labelKey),group:t(item.groupKey),subgroup:item.subgroupKey?t(item.subgroupKey):''})))},[t,jsonSortOpen,page])
  const record=(tool:ToolId,action:string,detail:string,input:string,output='',meta?:{mode?:string;mediaType?:string;name?:string;bytes?:number})=>{void AppendHistory({tool,action,detail:normalizeHistoryDetail(detail),mode:meta?.mode??'',mediaType:meta?.mediaType??'',name:meta?.name??'',bytes:meta?.bytes??new TextEncoder().encode(input).length,input,output}).then(item=>setHistory(current=>[item as HistoryItem,...current].slice(0,100))).catch(()=>toast(t('toast.historyFailed'),{variant:'danger'}))};const openTool=(id:ToolId,input?:string)=>{navigate(id);setPending(input===undefined?null:{tool:id,action:'restore',input})};const openHistory=async(item:HistoryItem)=>{try{const content=await GetHistoryContent(item.id);setPending({tool:item.tool,action:'restore',input:content.input,output:content.output,mode:item.mode});navigate(item.tool)}catch{toast(t('toast.historyFailed'),{variant:'danger'})}};const clearHistory=()=>{void ClearHistory().then(()=>setHistory([])).catch(()=>toast(t('toast.historyFailed'),{variant:'danger'}))};const cycleSidebar=()=>setSettings(s=>({...s,sidebarMode:s.sidebarMode==='full'?'icon':s.sidebarMode==='icon'?'hidden':'full'}));const openPalette=()=>{lastFocusedRef.current=document.activeElement;setPaletteOpen(true)};const pasteIntoFocused=async()=>{setPaletteOpen(false);const text=(await Clipboard.Text().catch(()=>''))||'';if(!text.trim()){toast(t('toast.clipboardEmpty'),{description:t('toast.clipboardEmptyDesc'),variant:'warning'});return}const target=lastFocusedRef.current;if(!(target instanceof HTMLElement)||(!target.isContentEditable&&target.tagName!=='INPUT'&&target.tagName!=='TEXTAREA')){toast(t('toast.pasteTarget'),{variant:'warning'});return}requestAnimationFrame(()=>{target.focus();document.execCommand('insertText',false,text)})}
  const run=(item:IndexedItem)=>{if(item.action==='paste'){void pasteIntoFocused();return}setPaletteOpen(false);if(!item.tool){setPending(null);navigate(item.page??'home');return}const tool=item.tool;const action=item.action??'open';const needsInput=!!item.needsInput;const apply=async()=>{let input='';if(needsInput){input=(await Clipboard.Text().catch(()=>''))||'';if(!input.trim()){setPending(null);navigate(tool);toast(t('toast.clipboardEmpty'),{description:t('toast.clipboardEmptyDesc'),variant:'warning'});return}}if(tool==='diff'&&action==='fill'&&item.target==='alternate'){const t=nextDiffTarget.current;nextDiffTarget.current=t==='before'?'after':'before';setPending({tool,action,input,target:t});navigate(tool);return}setPending({tool,action,input,mode:item.mode,target:item.target==='alternate'?undefined:item.target});navigate(tool)};apply()}
  const analyzeClipboard=async()=>{if(!settings.trayMatchEnabled)return;const text=(await Clipboard.Text().catch(()=>''))||'';const s=text.trim();if(!s)return;let tool:ToolId='text';let mode:string|undefined;let target:'before'|'after'|undefined;mode=detectBase64(s)??undefined;if(mode)tool='base64';else if(parseTimeInput(s))tool='time';else try{parseJsonLoose(s);if(page==='diff'){tool='diff';target=settings.diffClipboardTargetMode==='before'?'before':settings.diffClipboardTargetMode==='after'?'after':nextDiffTarget.current}else tool='json'}catch{}const apply=(match:{tool:ToolId;input:string;mode?:string;target?:'before'|'after'})=>{if(match.tool==='diff'&&match.target&&settings.diffClipboardTargetMode==='alternate')nextDiffTarget.current=match.target==='before'?'after':'before';setPending({tool:match.tool,action:'open',input:match.input,mode:match.mode,target:match.target});navigate(match.tool)};const match={tool,input:text,mode,target};if(settings.autoOverwrite)apply(match);else setMatchDialog(match)}
  return <>
    <AppToastProvider/>
    <div className="app-shell">
      <div className="ambient"/>
      <header className="titlebar" data-wails-drag><button className="sidebar-toggle" onClick={cycleSidebar} aria-label={t('sidebar.toggle')} title={t('sidebar.toggle')}><SidebarSimple size={16} weight="duotone"/></button><div className="titlebar-navigation"><button className="titlebar-navigation-button" onClick={()=>window.history.back()} aria-label={t('titlebar.back')} title={t('titlebar.back')}><ArrowLeft size={15} weight="duotone"/></button><button className="titlebar-navigation-button" onClick={()=>window.history.forward()} aria-label={t('titlebar.forward')} title={t('titlebar.forward')}><ArrowRight size={15} weight="duotone"/></button></div></header>
      <div className={`main sidebar-${sidebarMode}`}><Sidebar page={page} onNavigate={navigate} onOpenPalette={openPalette}/><main className={`workspace${tools.some(tool=>tool.id===page)?' overflow-y-hidden':''}`} ref={workspaceRef}>{page==='home'&&<Home favorites={favorites} history={history} openHistory={openHistory} openTool={openTool} toggleFavorite={id=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/>} <div className={`tool-slot${page==='json'?'':' hidden'}`}><JsonTool active={page==='json'} theme={theme} record={record} pending={pending} clearPending={()=>setPending(null)} onSortOpenChange={setJsonSortOpen}/></div><div className={`tool-slot${page==='time'?'':' hidden'}`}><TimeTool active={page==='time'} record={record} pending={pending} clearPending={()=>setPending(null)}/></div><div className={`tool-slot${page==='text'?'':' hidden'}`}><TextTool active={page==='text'} theme={theme} record={record} pending={pending} clearPending={()=>setPending(null)}/></div><div className={`tool-slot${page==='base64'?'':' hidden'}`}><Base64Tool active={page==='base64'} theme={theme} record={record} pending={pending} clearPending={()=>setPending(null)}/></div><div className={`tool-slot${page==='diff'?'':' hidden'}`}><DiffTool active={page==='diff'} theme={theme} highlightMode={settings.diffHighlightMode} onHighlightModeChange={(diffHighlightMode:HighlightMode)=>setSettings(current=>({...current,diffHighlightMode}))} clipboardTargetMode={settings.diffClipboardTargetMode} onClipboardTargetModeChange={diffClipboardTargetMode=>setSettings(current=>({...current,diffClipboardTargetMode}))} record={record} pending={pending} clearPending={()=>setPending(null)}/></div> {page==='settings'&&<SettingsPage settings={settings} setSettings={setSettings} theme={theme} clearHistory={clearHistory}/>} {page==='history'&&<HistoryPage openHistory={openHistory} clear={clearHistory}/>}</main></div>
      <CommandPalette open={paletteOpen} onClose={()=>setPaletteOpen(false)} indexed={indexed} run={run} page={page}/>
    </div>
    <AlertDialog.Backdrop isOpen={matchDialog!==null} onOpenChange={open=>{if(!open)setMatchDialog(null)}}><AlertDialog.Container><AlertDialog.Dialog className="json-comment-dialog"><AlertDialog.CloseTrigger/><AlertDialog.Header><AlertDialog.Icon status="accent"/><AlertDialog.Heading>{t('matchDialog.title')}</AlertDialog.Heading></AlertDialog.Header><AlertDialog.Body><p>{t('matchDialog.bodyPrefix')}<strong>{matchDialog?t(`tools.${matchDialog.tool}.name`):''}</strong>{t('matchDialog.bodySuffix')}</p></AlertDialog.Body><AlertDialog.Footer><Button variant="tertiary" onPress={()=>setMatchDialog(null)}>{t('matchDialog.cancel')}</Button><Button variant="primary" onPress={()=>{const d=matchDialog;setMatchDialog(null);if(d){if(d.tool==='diff'&&d.target&&settings.diffClipboardTargetMode==='alternate')nextDiffTarget.current=d.target==='before'?'after':'before';setPending({tool:d.tool,action:'open',input:d.input,mode:d.mode,target:d.target});navigate(d.tool)}}}>{t('matchDialog.confirm')}</Button></AlertDialog.Footer></AlertDialog.Dialog></AlertDialog.Container></AlertDialog.Backdrop>
  </>
}

function CommandPalette({open,onClose,indexed,run,page}:{open:boolean;onClose:()=>void;indexed:IndexedItem[];run:(item:IndexedItem)=>void;page:Page}){
  const{t}=useTranslation();const[input,setInput]=useState('');const[active,setActive]=useState(0)
  useEffect(()=>{if(open){setInput('');setActive(0)}},[open])
  const matches=useMemo(()=>{const q=input.trim().toLowerCase().replace(/\s+/g,'');if(!q)return null;const rank=(i:IndexedItem)=>i.tool&&i.tool===page?0:i.page?1:2;const scored:Array<{item:IndexedItem;score:number}>=[];for(const item of indexed){const score=Math.max(fuzzyScore(item.text,q),fuzzyScore(item.pinyin,q)*.95,fuzzyScore(item.initials,q)*.9);if(score>0)scored.push({item,score})}scored.sort((a,b)=>rank(a.item)-rank(b.item)||b.score-a.score);return scored.map(s=>s.item)},[input,indexed,page])
  const list=matches??indexed
  useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(a=>list.length?Math.min(a+1,list.length-1):0)}else if(e.key==='ArrowUp'){e.preventDefault();setActive(a=>list.length?Math.max(a-1,0):0)}else if(e.key==='Enter'){e.preventDefault();const item=list[active];if(item)run(item)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[open,active,list])
  useLayoutEffect(()=>{if(open)document.getElementById(`palette-opt-${active}`)?.scrollIntoView({block:'nearest'})},[open,active,list])
  if(!open)return null
  return <div className="palette-backdrop" onClick={onClose}><div className="palette-card" onClick={event=>event.stopPropagation()}><div className="palette-input"><MagnifyingGlass size={18} weight="duotone"/><input autoFocus spellCheck={false} role="combobox" aria-expanded={list.length>0} aria-controls="palette-listbox" aria-activedescendant={list.length?`palette-opt-${active}`:undefined} aria-label={t('palette.searchLabel')} value={input} onChange={e=>{setInput(e.target.value);setActive(0)}} placeholder={t('palette.searchPlaceholder')}/></div>{list.length>0?<div className="palette-list" id="palette-listbox" role="listbox" aria-label={t('palette.listLabel')}>{list.map((item,i)=><button key={item.id} id={`palette-opt-${i}`} role="option" aria-selected={i===active} className={`palette-row${i===active?' active':''}`} onMouseMove={e=>{if(e.nativeEvent.movementX||e.nativeEvent.movementY)setActive(i)}} onClick={()=>run(item)}><span className="palette-item"><item.icon size={16} weight="duotone"/><span className="palette-label">{t(item.labelKey)}</span><small>{t(item.groupKey)}{item.subgroupKey?` - ${t(item.subgroupKey)}`:''}</small></span></button>)}</div>:<div className="palette-list palette-empty" role="status"><span>{t('palette.empty')}</span></div>}</div></div>
}

function Sidebar({page,onNavigate,onOpenPalette}:{page:Page;onNavigate:(p:Page)=>void;onOpenPalette:()=>void}){const{t}=useTranslation();return <aside className="sidebar"><nav aria-label={t('groups.tools')}><div className="sidebar-heading">{t('groups.tools')}</div>{tools.map(tool=><button key={tool.id} className={`sidebar-item${page===tool.id?' active':''}`} aria-current={page===tool.id?'page':undefined} aria-label={t(tool.nameKey)} title={t(tool.nameKey)} onClick={()=>onNavigate(tool.id)}><tool.icon size={17} weight="duotone"/><span>{t(tool.nameKey)}</span></button>)}</nav><nav aria-label={t('titlebar.nav')}><div className="sidebar-heading">{t('titlebar.nav')}</div><button className={`sidebar-item${page==='history'?' active':''}`} aria-current={page==='history'?'page':undefined} aria-label={t('titlebar.history')} title={t('titlebar.history')} onClick={()=>onNavigate('history')}><ClockCounterClockwise size={17} weight="duotone"/><span>{t('titlebar.history')}</span></button><button className={`sidebar-item${page==='settings'?' active':''}`} aria-current={page==='settings'?'page':undefined} aria-label={t('titlebar.settings')} title={t('titlebar.settings')} onClick={()=>onNavigate('settings')}><GearSix size={17} weight="duotone"/><span>{t('titlebar.settings')}</span></button></nav><div className="sidebar-footer"><button className="sidebar-palette" onClick={onOpenPalette} aria-label={t('statusbar.openPalette')} title={t('statusbar.openPalette')}><MagnifyingGlass className="palette-icon" size={14} weight="duotone"/><kbd>{navigator.platform.includes('Mac')?'⌘':'Ctrl'}</kbd><kbd>K</kbd><span>{t('statusbar.openPalette')}</span></button></div></aside>}
function HistoryIcon({tool}:{tool:ToolId}){return tool==='json'?<BracketsCurly weight="duotone"/>:tool==='time'?<Clock weight="duotone"/>:tool==='base64'?<FileCode weight="duotone"/>:tool==='diff'?<GitDiff weight="duotone"/>:<TextT weight="duotone"/>}
function Home({favorites,history,openTool,openHistory,toggleFavorite}:{favorites:ToolId[];history:HistoryItem[];openTool:(id:ToolId,input?:string)=>void;openHistory:(item:HistoryItem)=>void;toggleFavorite:(id:ToolId)=>void}){const{t}=useTranslation();return <section className="home-page">{history.length>0&&<Reveal index={0}><section className="recent-strip"><div className="section-heading"><span>{t('home.recent')}</span></div>{history.slice(0,2).map((item,idx)=><button key={item.id} className="recent-row" style={{'--index':idx} as React.CSSProperties} onClick={()=>void openHistory(item)}><span className="recent-icon"><HistoryIcon tool={item.tool}/></span><span><strong>{item.action}</strong><small>{item.detail}</small></span><time>{formatRelative(item.at,t)}</time><CaretRight size={14} weight="duotone"/></button>)}</section></Reveal>}<Reveal index={1}><ToolSection title={t('home.tools')} toolsToShow={tools} favorites={favorites} openTool={openTool} toggleFavorite={toggleFavorite}/></Reveal></section>}
function ToolSection({title,subtitle,toolsToShow,favorites,openTool,toggleFavorite}:{title:string;subtitle?:string;toolsToShow:typeof tools;favorites:ToolId[];openTool:(id:ToolId,input?:string)=>void;toggleFavorite:(id:ToolId)=>void}){const{t}=useTranslation();return <section className="tool-list"><div className="section-heading"><span>{title}</span>{subtitle?<span>{subtitle}</span>:null}</div>{toolsToShow.map((tool,index)=><div className="tool-row" key={tool.id} style={{'--index':index} as React.CSSProperties}><button className="tool-main" onClick={()=>openTool(tool.id)}><span className="tool-icon"><tool.icon size={21} weight="duotone"/></span><span><strong>{t(tool.nameKey)}</strong><small>{t(tool.descriptionKey)}</small></span></button><button className={`favorite ${favorites.includes(tool.id)?'selected':''}`} onClick={()=>toggleFavorite(tool.id)} aria-label={favorites.includes(tool.id)?t('home.removeFavorite'):t('home.addFavorite')}><Heart size={16} weight={favorites.includes(tool.id)?'fill':'duotone'}/></button><CaretRight className="row-caret" size={16} weight="duotone"/></div>)}</section>}
function SettingSwitch({selected,onChange}:{selected:boolean;onChange:(v:boolean)=>void}){return <Switch isSelected={selected} onChange={onChange}><Switch.Content><Switch.Control><Switch.Thumb/></Switch.Control></Switch.Content></Switch>}
function ClearHistoryDialog({open,onClose,onConfirm}:{open:boolean;onClose:()=>void;onConfirm:()=>void}){const{t}=useTranslation();return <AlertDialog.Backdrop isOpen={open} onOpenChange={o=>{if(!o)onClose()}}><AlertDialog.Container><AlertDialog.Dialog className="json-comment-dialog"><AlertDialog.CloseTrigger/><AlertDialog.Header><AlertDialog.Icon status="danger"/><AlertDialog.Heading>{t('clearHistoryDialog.title')}</AlertDialog.Heading></AlertDialog.Header><AlertDialog.Body><p>{t('clearHistoryDialog.body')}</p></AlertDialog.Body><AlertDialog.Footer><Button variant="tertiary" onPress={onClose}>{t('clearHistoryDialog.cancel')}</Button><Button variant="danger" onPress={()=>{onConfirm();onClose()}}>{t('clearHistoryDialog.confirm')}</Button></AlertDialog.Footer></AlertDialog.Dialog></AlertDialog.Container></AlertDialog.Backdrop>}
function SettingsPage({settings,setSettings,theme,clearHistory}:{settings:Settings;setSettings:React.Dispatch<React.SetStateAction<Settings>>;theme:string;clearHistory:()=>void}){const{t}=useTranslation();const[confirmClear,setConfirmClear]=useState(false);const update=(key:BooleanSettingKey,value:boolean)=>setSettings(current=>({...current,[key]:value}));const setTheme=(value:'dark'|'light')=>setSettings(current=>({...current,theme:value}));const setLanguage=(code:string)=>{setSettings(current=>({...current,language:code}));i18n.changeLanguage(code)};return <Reveal index={0}><section className="settings-page"><header className="page-title"><h1>{t('settings.title')}</h1><p>{t('settings.subtitle')}</p></header><SettingsGroup title={t('settings.appearance')} subtitle={t('settings.appearanceSubtitle')}><Setting label={t('settings.theme')}><div className="segmented language-switch">{[['dark',t('settings.themeDark')],['light',t('settings.themeLight')]].map(([value,label])=><button key={value} className={theme===value?'active':''} onClick={()=>setTheme(value as 'dark'|'light')}>{label}</button>)}</div></Setting></SettingsGroup><SettingsGroup title={t('settings.editor')} subtitle={t('settings.editorSubtitle')}><Setting label={t('settings.editorFontSize')}><div className="segmented language-switch">{[12,14,16,18].map(size=><button key={size} className={(settings.codeEditorFontSize||12)===size?'active':''} onClick={()=>setSettings(current=>({...current,codeEditorFontSize:size}))}>{size}px</button>)}</div></Setting></SettingsGroup><SettingsGroup title={t('settings.language')} subtitle={t('settings.languageSubtitle')}><Setting label={t(`settings.languages.${settings.language}`)}><div className="segmented language-switch">{SUPPORTED_LANGUAGES.map(l=><button key={l.code} className={settings.language===l.code?'active':''} onClick={()=>setLanguage(l.code)}>{t(l.labelKey)}</button>)}</div></Setting></SettingsGroup><SettingsGroup title={t('settings.clipboard')} subtitle={t('settings.clipboardSubtitle')}><Setting label={t('settings.trayMatch')} description={t('settings.trayMatchDesc')}><SettingSwitch selected={settings.trayMatchEnabled} onChange={v=>update('trayMatchEnabled',v)}/></Setting><Setting label={t('settings.autoOverwrite')} description={t('settings.autoOverwriteDesc')}><SettingSwitch selected={settings.autoOverwrite} onChange={v=>update('autoOverwrite',v)}/></Setting></SettingsGroup><SettingsGroup title={t('settings.privacy')} subtitle={t('settings.privacySubtitle')}><Setting label={t('settings.history')} description={t('settings.historyDesc')}><Button variant="danger-soft" onPress={()=>setConfirmClear(true)}><Trash weight="duotone"/>{t('settings.clearHistory')}</Button></Setting></SettingsGroup></section><ClearHistoryDialog open={confirmClear} onClose={()=>setConfirmClear(false)} onConfirm={clearHistory}/></Reveal>}
function SettingsGroup({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="settings-group"><div><h2>{title}</h2><p>{subtitle}</p></div><div className="settings-list">{children}</div></section>}
function Setting({label,description,children}:{label:string;description?:string;children:React.ReactNode}){return <div className="setting"><span><strong>{label}</strong>{description&&<small>{description}</small>}</span>{children}</div>}
function HistoryPage({openHistory,clear}:{openHistory:(item:HistoryItem)=>void;clear:()=>void}){const{t}=useTranslation();const[confirmClear,setConfirmClear]=useState(false);const[items,setItems]=useState<HistoryItem[]>([]);const[total,setTotal]=useState(0);const[loading,setLoading]=useState(false);const[error,setError]=useState(false);const sentinel=useRef<HTMLDivElement>(null);const loadMore=async()=>{if(loading)return;setLoading(true);try{const page=await GetHistoryPage(items.length,30);setItems(prev=>[...prev,...(page.items??[]).map(toHistoryItem).filter((x):x is HistoryItem=>x!==null)]);setTotal(page.total)}catch{setError(true)}setLoading(false)};useEffect(()=>{void loadMore()},[]);useEffect(()=>{const el=sentinel.current;if(!el||items.length>=total||loading)return;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting)void loadMore()},{rootMargin:'240px'});observer.observe(el);return()=>observer.disconnect()},[items.length,total,loading]);const clearAll=()=>{clear();setItems([]);setTotal(0)};return <Reveal index={0}><section className="history-page"><header className="page-title row"><div><h1>{t('history.title')}</h1><p>{t('history.subtitle')}</p></div>{total>0&&<Button variant="tertiary" onPress={()=>setConfirmClear(true)}><Trash weight="duotone"/>{t('history.clear')}</Button>}</header>{items.length?<div className="history-list">{items.map((item,idx)=><button key={item.id} style={{'--index':idx} as React.CSSProperties} onClick={()=>void openHistory(item)}><span className="history-tool"><HistoryIcon tool={item.tool}/></span><span><strong>{item.action}</strong><small>{item.detail}</small></span><time>{formatRelative(item.at,t)}</time><CaretRight weight="duotone"/></button>)}</div>:error?<button className="empty-state history-empty" onClick={()=>{setError(false);void loadMore()}}><Hash size={28} weight="duotone"/><strong>{t('history.loadFailed')}</strong><span>{t('history.loadFailedHint')}</span></button>:<div className="empty-state history-empty"><Hash size={28} weight="duotone"/><strong>{t('history.emptyTitle')}</strong><span>{t('history.emptyHint')}</span></div>}<div ref={sentinel} className={`history-more${loading||items.length<total?'':' hidden'}`}>{loading?<span className="history-more-spinner" aria-hidden="true"/>:null}</div></section><ClearHistoryDialog open={confirmClear} onClose={()=>setConfirmClear(false)} onConfirm={clearAll}/></Reveal>}
export default App
